/// @file gs_efx_chain_fixture_test.cpp
/// @brief Byte-identity fixture for the insertion-effect chain skeleton.
///
/// gs_efx_insert_chain answers two questions at once: which stages a type
/// realises, and what each stage is configured with. Restructuring the second
/// half -- moving a parameter's translation from a hand-written branch onto a
/// table -- is meant to leave the first half untouched, and nothing else in the
/// suite can see the difference: the type case checks that a chain exists and
/// the join case checks one key at a time, so a stage silently gaining or
/// losing a parameter passes both.
///
/// The fixture sweeps every declared type over every slot at the boundary
/// bytes and records the whole rendering. A cell is written down only where it
/// differs from the type's own power-on chain, which is what keeps the file
/// readable: a byte no type reads changes nothing and says so by its absence.

#include <array>
#include <catch2/catch_test_macros.hpp>
#include <cstdint>
#include <cstdlib>
#include <filesystem>
#include <fstream>
#include <map>
#include <sstream>
#include <string>
#include <vector>

#include "midi/synth/gs_efx_tables.h"
#include "midi/synth/gs_layer.h"

namespace {

using sonare::midi::synth::gs_efx_insert_chain;
using sonare::midi::synth::gs_efx_type_defaults;
using sonare::midi::synth::GsEfx;
using sonare::midi::synth::GsEfxStage;
using sonare::midi::synth::kGsEfxTypeDefaults;

/// The byte values the boundary axis takes: the two ends, the centre and its
/// neighbours, which is where every conversion in the archive has a knot. The
/// same seven the join case sweeps.
constexpr std::array<uint8_t, 7> kValues = {0, 1, 63, 64, 65, 126, 127};

constexpr int kSlots = 20;

/// Where the recorded sweep lives. Regenerated by running this case with
/// SONARE_UPDATE_GS_EFX_CHAIN_FIXTURE set; the diff is the evidence that a
/// restructuring moved what it meant to move.
constexpr const char* kFixturePath = "tests/midi/gs_efx_chain_fixture.tsv";

/// A unit holding @p type in the state selecting it over the wire leaves: the
/// type's own twenty power-on parameters, not a block of zeros.
GsEfx make_efx(uint16_t type) {
  GsEfx efx;
  efx.type = type;
  efx.type_msb = static_cast<uint8_t>(type >> 8);
  const auto* defaults = gs_efx_type_defaults(type);
  if (defaults != nullptr) efx.params = defaults->params;
  efx.assigned = true;
  return efx;
}

/// One line holding the whole chain: every stage name and its parameters, in
/// order. An empty chain renders as the empty string, which is what an unmapped
/// type is and is distinguishable from a one-stage chain with no parameters.
std::string render(const std::vector<GsEfxStage>& chain) {
  std::string out;
  for (const GsEfxStage& stage : chain) {
    if (!out.empty()) out += " | ";
    out += stage.name;
    out += ' ';
    out += stage.params_json;
  }
  return out;
}

std::string hex4(uint16_t value) {
  static const char* kDigits = "0123456789abcdef";
  std::string out(4, '0');
  for (int i = 3; i >= 0; --i) {
    out[static_cast<size_t>(i)] = kDigits[value & 0xFu];
    value = static_cast<uint16_t>(value >> 4);
  }
  return out;
}

/// A swept cell's address, as it is spelled in the fixture. Slot and value are
/// -1 on the row carrying the type's own power-on chain.
struct Cell {
  std::string type;
  int slot;
  int value;

  bool operator<(const Cell& other) const {
    if (type != other.type) return type < other.type;
    if (slot != other.slot) return slot < other.slot;
    return value < other.value;
  }
};

using Sweep = std::map<Cell, std::string>;

Sweep compute_sweep() {
  Sweep sweep;
  for (const auto& row : kGsEfxTypeDefaults) {
    const std::string type = hex4(row.type);
    const std::string baseline = render(gs_efx_insert_chain(make_efx(row.type)));
    sweep[{type, -1, -1}] = baseline;
    for (int slot = 0; slot < kSlots; ++slot) {
      for (uint8_t value : kValues) {
        GsEfx efx = make_efx(row.type);
        efx.params[static_cast<size_t>(slot)] = value;
        const std::string moved = render(gs_efx_insert_chain(efx));
        // Only the bytes a type actually reads are written down. The rest are
        // the majority, and recording them would bury the ones that matter.
        if (moved != baseline) sweep[{type, slot, static_cast<int>(value)}] = moved;
      }
    }
  }
  return sweep;
}

void write_fixture(const std::filesystem::path& path, const Sweep& sweep) {
  std::ofstream file(path);
  file << "# type\tslot\tvalue\tchain\n";
  file << "# slot -1 value -1 is the type's own power-on chain; every other row\n";
  file << "# is a boundary byte whose chain differs from it.\n";
  for (const auto& [cell, chain] : sweep) {
    file << cell.type << '\t' << cell.slot << '\t' << cell.value << '\t' << chain << '\n';
  }
}

Sweep read_fixture(const std::filesystem::path& path) {
  Sweep sweep;
  std::ifstream file(path);
  REQUIRE(file.good());
  std::string line;
  while (std::getline(file, line)) {
    if (line.empty() || line[0] == '#') continue;
    std::istringstream fields(line);
    Cell cell;
    std::string slot;
    std::string value;
    std::string chain;
    REQUIRE(std::getline(fields, cell.type, '\t'));
    REQUIRE(std::getline(fields, slot, '\t'));
    REQUIRE(std::getline(fields, value, '\t'));
    // The chain is the rest of the line, including nothing at all for an
    // unmapped type -- getline fails on an empty tail, which is not an error.
    std::getline(fields, chain);
    cell.slot = std::stoi(slot);
    cell.value = std::stoi(value);
    sweep[cell] = chain;
  }
  return sweep;
}

}  // namespace

TEST_CASE("the EFX chain skeleton renders the same bytes over every slot and boundary value",
          "[midi][sf2][gs][efxtypes]") {
  const std::filesystem::path path = kFixturePath;
  const Sweep observed = compute_sweep();

  if (std::getenv("SONARE_UPDATE_GS_EFX_CHAIN_FIXTURE") != nullptr) {
    write_fixture(path, observed);
  }
  const Sweep expected = read_fixture(path);

  // The sweep is only evidence if it moved something. A fixture holding one
  // baseline row per type and no boundary rows would compare a constant to
  // itself for every type in the block and could not go red on a translation.
  int baselines = 0;
  int moved = 0;
  for (const auto& [cell, chain] : observed) {
    (void)chain;
    (cell.slot < 0 ? baselines : moved) += 1;
  }
  REQUIRE(baselines == static_cast<int>(kGsEfxTypeDefaults.size()));
  REQUIRE(moved > 0);

  // Checked rather than required: how far a drift spread -- one type or the
  // whole block -- is what separates a restructuring from a regression, and a
  // required row hides that at the first one.
  for (const auto& [cell, chain] : observed) {
    CAPTURE(cell.type, cell.slot, cell.value);
    const auto it = expected.find(cell);
    CHECK(it != expected.end());
    if (it != expected.end()) CHECK(it->second == chain);
  }
  for (const auto& [cell, chain] : expected) {
    (void)chain;
    CAPTURE(cell.type, cell.slot, cell.value);
    CHECK(observed.count(cell) == 1);
  }
}
