// Generated by tools/gs/derive_efx_tables.py from tools/gs/efx-tables.json -- do not edit.
//
// The byte-to-physical-quantity conversions the GS insertion-effect parameter
// block uses, derived from an archive of what one individual SC-8850 answered.
// Nothing here is a sample-rate coefficient: every quantity is Hz, ms, seconds,
// decibels or a ratio, and a coefficient is built in prepare().
//
// tools/gs/docs/efx-tables.md says how the tables are read and what they
// cannot see. tools/gs/efx-tables.json carries the provenance of each entry.

#pragma once

#include <array>
#include <cstdint>
#include <string_view>

namespace sonare::midi::synth {

inline constexpr std::string_view kGsEfxUnitId = "roland-sc8850-01";
inline constexpr std::string_view kGsEfxArchiveRevision =
    "0860b74681d4e6f4f0f8ab2fe84d0abf69e9edb0";

/// A (setting, value) knot of a piecewise-linear table.
struct GsEfxBreakpoint {
  uint8_t setting;
  float value;
};

/// One (type, slot) pair the archive gives a conversion to.
struct GsEfxSlotConversion {
  uint16_t type;             ///< The two type bytes, MSB in the high byte.
  uint8_t parameter;         ///< Slot index from the first parameter address.
  uint8_t conversion_class;  ///< One of the kGsEfxClass* values below.
  uint8_t table;             ///< Which table of that class; see the JSON.
};

/// The twenty bytes a type powers up holding, and which of them were measured.
struct GsEfxTypeDefaults {
  uint16_t type;
  uint32_t measured;  ///< Bit i set where slot i carries a measured byte.
  std::array<uint8_t, 20> params;
};

// How far the archive reaches, per conversion class. A class reaching zero is a
// failure of the derivation and not a property of the unit.
inline constexpr int kGsEfxReachRate = 21;
inline constexpr uint8_t kGsEfxClassRate = 0;
inline constexpr int kGsEfxReachDelayTime = 23;
inline constexpr uint8_t kGsEfxClassDelayTime = 1;
inline constexpr int kGsEfxReachFreq = 7;
inline constexpr uint8_t kGsEfxClassFreq = 2;
inline constexpr int kGsEfxReachGain = 14;
inline constexpr uint8_t kGsEfxClassGain = 3;
inline constexpr int kGsEfxReachLevel = 3;
inline constexpr uint8_t kGsEfxClassLevel = 4;
inline constexpr int kGsEfxReachWidth = 4;
inline constexpr uint8_t kGsEfxClassWidth = 5;
inline constexpr int kGsEfxReachWave = 3;
inline constexpr uint8_t kGsEfxClassWave = 6;
inline constexpr int kGsEfxReachPan = 3;
inline constexpr uint8_t kGsEfxClassPan = 7;
inline constexpr int kGsEfxReachBalance = 3;
inline constexpr uint8_t kGsEfxClassBalance = 8;
inline constexpr int kGsEfxReachAzimuth = 2;
inline constexpr uint8_t kGsEfxClassAzimuth = 9;
inline constexpr int kGsEfxReachAccel = 2;
inline constexpr uint8_t kGsEfxClassAccel = 10;
inline constexpr int kGsEfxReachPostGain = 2;
inline constexpr uint8_t kGsEfxClassPostGain = 11;
inline constexpr int kGsEfxReachWindow = 2;
inline constexpr uint8_t kGsEfxClassWindow = 12;

// The two numbers the block's coverage is read as: every (type, slot) the unit
// prints a value for, and how many of those these tables give a conversion to.
// Held apart because the numerator alone reads as an amount understood, which
// it is not, and because one number cannot say which of the two moved.
inline constexpr int kGsEfxPrinted = 770;
inline constexpr int kGsEfxMeasured = 89;

// The same count per table. A class holds more than one -- two rate ranges, five
// delay ladders, three frequency columns -- so a table that stops being fed leaves
// its class's count untouched, which is the shape the class guard was written
// against. Named constants rather than an array, for the reason the class counts are:
// a check that reads a list the generator wrote passes by not looking.
inline constexpr int kGsEfxTableUseRateNarrow = 3;
inline constexpr int kGsEfxTableUseRateWide = 18;
inline constexpr int kGsEfxTableUseDelayTimePreDelay = 4;
inline constexpr int kGsEfxTableUseDelayTimeTime1 = 7;
inline constexpr int kGsEfxTableUseDelayTimeTime2 = 0;
inline constexpr int kGsEfxTableUseDelayTimeTime3 = 11;
inline constexpr int kGsEfxTableUseDelayTimeTime4 = 1;
inline constexpr int kGsEfxTableUseFreqEq = 4;
inline constexpr int kGsEfxTableUseFreqPreFilter = 1;
inline constexpr int kGsEfxTableUseFreqDamping = 2;
inline constexpr int kGsEfxTableUseGainTone = 14;
inline constexpr int kGsEfxTableUseLevelOutput = 3;
inline constexpr int kGsEfxTableUseWidthSection = 4;
inline constexpr int kGsEfxTableUseWaveModulator = 3;
inline constexpr int kGsEfxTableUsePanOutput = 3;
inline constexpr int kGsEfxTableUseBalanceEffect = 3;
inline constexpr int kGsEfxTableUseAzimuthPlacement = 2;
inline constexpr int kGsEfxTableUseAccelRotor = 2;
inline constexpr int kGsEfxTableUsePostGainMakeup = 2;
inline constexpr int kGsEfxTableUseWindowSplice = 2;

/// Rate, printed 0.05 - 6.40.
inline constexpr std::array<GsEfxBreakpoint, 2> kGsEfxRateNarrow = {{
    {0, 0.05f},
    {127, 6.4f},
}};

/// Rate, printed 0.05 - 10.00.
inline constexpr std::array<GsEfxBreakpoint, 5> kGsEfxRateWide = {{
    {0, 0.05f},
    {99, 5.0f},
    {119, 7.0f},
    {125, 10.0f},
    {127, 10.0f},
}};

/// The rate the unit's own delay ladders are cut to. Not a rendering rate.
inline constexpr int kGsEfxUnitClockHz = 32000;

/// Delay time, printed 0.0 - 100.
inline constexpr std::array<GsEfxBreakpoint, 6> kGsEfxDelayPreDelay = {{
    {0, 0.0f},
    {50, 5.0f},
    {60, 10.0f},
    {100, 50.0f},
    {125, 100.0f},
    {127, 100.0f},
}};

/// Delay time, printed 200 - 1000.
inline constexpr std::array<GsEfxBreakpoint, 4> kGsEfxDelayTime1 = {{
    {0, 200.0f},
    {70, 550.0f},
    {115, 1000.0f},
    {127, 1000.0f},
}};

/// Delay time, printed 200 - 1000.
inline constexpr std::array<GsEfxBreakpoint, 4> kGsEfxDelayTime2 = {{
    {0, 200.0f},
    {80, 600.0f},
    {120, 1000.0f},
    {127, 1000.0f},
}};

/// Delay time, printed 0.0 - 500.
inline constexpr std::array<GsEfxBreakpoint, 7> kGsEfxDelayTime3 = {{
    {0, 0.0f},
    {50, 5.0f},
    {60, 10.0f},
    {90, 40.0f},
    {116, 300.0f},
    {126, 500.0f},
    {127, 500.0f},
}};

/// Delay time, printed 0 - 635.
inline constexpr std::array<GsEfxBreakpoint, 2> kGsEfxDelayTime4 = {{
    {0, 0.0f},
    {127, 635.0f},
}};

/// The 16th entry of a frequency column the unit prints a bypass against.
inline constexpr float kGsEfxFreqBypass = 0.0f;
/// Frequency, printed 200 - 6.3k.
inline constexpr std::array<float, 16> kGsEfxFreqEq = {{
    198.4f,
    240.5f,
    279.1f,
    397.9f,
    481.4f,
    600.0f,
    778.1f,
    977.3f,
    1224.4f,
    1585.0f,
    1952.3f,
    2468.9f,
    3105.0f,
    3948.8f,
    4931.8f,
    6166.8f,
}};

/// Frequency, printed 250 - 8k.
inline constexpr std::array<float, 16> kGsEfxFreqPreFilter = {{
    250.0f,
    315.0f,
    400.0f,
    500.0f,
    630.0f,
    800.0f,
    1000.0f,
    1250.0f,
    1600.0f,
    2000.0f,
    2500.0f,
    3150.0f,
    4000.0f,
    5000.0f,
    6300.0f,
    8000.0f,
}};

/// Frequency, printed 315 - 8k/Bypass.
inline constexpr std::array<float, 16> kGsEfxFreqDamping = {{
    312.9f,
    398.7f,
    500.0f,
    622.2f,
    801.2f,
    1000.0f,
    1245.4f,
    1600.0f,
    2016.6f,
    2500.0f,
    3138.3f,
    4000.0f,
    4964.3f,
    6300.0f,
    7972.9f,
    kGsEfxFreqBypass,
}};

// Gain: decibels a step over a window, nearest edge outside it.
inline constexpr uint8_t kGsEfxGainWindowLo = 52;
inline constexpr uint8_t kGsEfxGainWindowHi = 76;
inline constexpr int kGsEfxGainOffset = 64;
inline constexpr float kGsEfxGainDbPerStep = 1.0f;

// Output level: a stored numerator over 127. No closed form crosses this curve.
inline constexpr uint8_t kGsEfxLevelDenominator = 127;
inline constexpr std::array<uint8_t, 128> kGsEfxLevelNumerator = {{
    0,   1,   1,   2,   3,   4,   4,   5,   6,   6,   7,   8,   9,   9,   10,  11,  12,  12,  13,
    14,  15,  15,  16,  17,  18,  19,  19,  20,  21,  22,  23,  23,  24,  25,  26,  27,  28,  28,
    29,  30,  31,  32,  33,  34,  34,  35,  36,  37,  38,  39,  40,  41,  42,  43,  44,  44,  45,
    46,  47,  48,  49,  50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
    65,  66,  67,  68,  70,  71,  72,  73,  74,  75,  76,  77,  78,  79,  81,  82,  83,  84,  85,
    86,  87,  89,  90,  91,  92,  93,  95,  96,  97,  98,  99,  101, 102, 103, 104, 106, 107, 108,
    110, 111, 112, 114, 115, 116, 117, 119, 120, 122, 123, 124, 126, 127,
}};

/// Section width at the half-gain points. Settings past the table return entry 0.
inline constexpr std::array<float, 5> kGsEfxWidth = {{
    0.25f,
    0.5f,
    1.0f,
    2.0f,
    4.5f,
}};

// Modulation shapes. The fraction of the cycle that climbs separates the two saws;
// the third harmonic is what separates entry 2 from a plain sine.
inline constexpr std::array<float, 5> kGsEfxWaveRisingFraction = {{
    0.5f,
    0.3516f,
    0.4688f,
    0.8828f,
    0.1094f,
}};
inline constexpr std::array<float, 5> kGsEfxWaveThirdHarmonic = {{
    0.0f,
    0.0f,
    0.06f,
    0.0f,
    0.0f,
}};

/// Output pan, the left side's multiplier, the added term taken off.
inline constexpr std::array<GsEfxBreakpoint, 18> kGsEfxPanLeft = {{
    {0, 1.001f},
    {1, 1.0f},
    {8, 0.979141f},
    {16, 0.949046f},
    {24, 0.927557f},
    {32, 0.903376f},
    {40, 0.872693f},
    {48, 0.835437f},
    {56, 0.790175f},
    {64, 0.754909f},
    {72, 0.707822f},
    {80, 0.651537f},
    {88, 0.591701f},
    {96, 0.518187f},
    {104, 0.432559f},
    {112, 0.32774f},
    {120, 0.18725f},
    {126, 0.059583f},
}};

/// Output pan, the right side's multiplier, the added term taken off.
inline constexpr std::array<GsEfxBreakpoint, 18> kGsEfxPanRight = {{
    {1, 0.059017f},
    {8, 0.21119f},
    {16, 0.34676f},
    {24, 0.450704f},
    {32, 0.529286f},
    {40, 0.600908f},
    {48, 0.665236f},
    {56, 0.708199f},
    {64, 0.756399f},
    {72, 0.803473f},
    {80, 0.84064f},
    {88, 0.875925f},
    {96, 0.902617f},
    {104, 0.933513f},
    {112, 0.954793f},
    {120, 0.979115f},
    {126, 1.0f},
    {127, 0.996956f},
}};

// Balance: two truncated ramps offset so they meet at full rather than crossing.
inline constexpr int kGsEfxBalanceCornerEffect = 114;
inline constexpr int kGsEfxBalanceCornerDirect = 14;
inline constexpr int kGsEfxBalanceWidth = 50;
inline constexpr int kGsEfxBalanceGrid = 128;

// Azimuth: two added, shifted right two, recentred, clamped. 31 places, two of them one.
inline constexpr int kGsEfxAzimuthClamp = 15;
inline constexpr int kGsEfxAzimuthDegreesPerPosition = 12;

// Rotary acceleration: the divisor the rotor's loop divides its rate gap by, from the
// top four bits. Held as a divisor and turned into seconds by the shift below, never
// as a per-step coefficient -- that would move the time constant with the sample rate.
inline constexpr int kGsEfxAccelShift = 32768;
inline constexpr std::array<float, 16> kGsEfxAccelDivisor = {{
    1.0f,
    2.0f,
    3.0f,
    4.0f,
    5.0f,
    6.0f,
    7.0f,
    8.0f,
    9.0f,
    10.0f,
    12.0f,
    16.0f,
    32.0f,
    64.0f,
    128.0f,
    168.41f,
}};

// Post gain: fixed steps after the stage it is printed beside. Past the table, entry 0.
inline constexpr uint8_t kGsEfxPostGainSettings = 4;
inline constexpr float kGsEfxPostGainDbPerStep = 6.0f;

/// Splice window: how far the read-out drifts between splices. Past the table, entry 0.
inline constexpr std::array<float, 5> kGsEfxWindowMs = {{
    32.0f,
    42.6667f,
    64.0f,
    85.3333f,
    128.0f,
}};

/// Every (type, slot) pair the archive gives a conversion to.
inline constexpr std::array<GsEfxSlotConversion, 89> kGsEfxSlotConversions = {{
    {0x0100, 1, 3, 0},   // gain.tone
    {0x0100, 3, 3, 0},   // gain.tone
    {0x0100, 4, 2, 0},   // freq.eq
    {0x0100, 5, 5, 0},   // width.section
    {0x0100, 6, 3, 0},   // gain.tone
    {0x0100, 7, 2, 0},   // freq.eq
    {0x0100, 8, 5, 0},   // width.section
    {0x0100, 9, 3, 0},   // gain.tone
    {0x0100, 19, 4, 0},  // level.output
    {0x0101, 18, 7, 0},  // pan.output
    {0x0103, 18, 7, 0},  // pan.output
    {0x0111, 19, 4, 0},  // level.output
    {0x0120, 1, 0, 1},   // rate.wide
    {0x0121, 4, 0, 1},   // rate.wide
    {0x0122, 2, 10, 0},  // accel.rotor
    {0x0122, 6, 10, 0},  // accel.rotor
    {0x0123, 3, 0, 1},   // rate.wide
    {0x0125, 0, 6, 0},   // wave.modulator
    {0x0125, 1, 0, 1},   // rate.wide
    {0x0126, 0, 6, 0},   // wave.modulator
    {0x0126, 1, 0, 1},   // rate.wide
    {0x0130, 2, 11, 0},  // post_gain.makeup
    {0x0130, 18, 7, 0},  // pan.output
    {0x0131, 3, 11, 0},  // post_gain.makeup
    {0x0140, 0, 1, 0},   // delay_time.pre_delay
    {0x0140, 19, 4, 0},  // level.output
    {0x0142, 1, 2, 1},   // freq.pre_filter
    {0x0142, 3, 0, 1},   // rate.wide
    {0x0142, 16, 3, 0},  // gain.tone
    {0x0142, 17, 3, 0},  // gain.tone
    {0x0143, 1, 0, 1},   // rate.wide
    {0x0144, 1, 0, 1},   // rate.wide
    {0x0150, 0, 1, 3},   // delay_time.time3
    {0x0150, 1, 1, 3},   // delay_time.time3
    {0x0150, 7, 2, 2},   // freq.damping
    {0x0150, 15, 8, 0},  // balance.effect
    {0x0150, 16, 3, 0},  // gain.tone
    {0x0150, 17, 3, 0},  // gain.tone
    {0x0151, 0, 1, 3},   // delay_time.time3
    {0x0151, 1, 1, 3},   // delay_time.time3
    {0x0151, 4, 0, 1},   // rate.wide
    {0x0152, 0, 1, 1},   // delay_time.time1
    {0x0152, 1, 1, 1},   // delay_time.time1
    {0x0152, 2, 1, 1},   // delay_time.time1
    {0x0153, 0, 1, 1},   // delay_time.time1
    {0x0153, 1, 1, 1},   // delay_time.time1
    {0x0153, 2, 1, 1},   // delay_time.time1
    {0x0153, 3, 1, 1},   // delay_time.time1
    {0x0154, 15, 8, 0},  // balance.effect
    {0x0157, 0, 1, 3},   // delay_time.time3
    {0x0157, 1, 1, 3},   // delay_time.time3
    {0x0157, 2, 1, 3},   // delay_time.time3
    {0x0157, 15, 8, 0},  // balance.effect
    {0x0160, 8, 12, 0},  // window.splice
    {0x0161, 4, 12, 0},  // window.splice
    {0x0170, 0, 9, 0},   // azimuth.placement
    {0x0170, 1, 0, 1},   // rate.wide
    {0x0171, 0, 9, 0},   // azimuth.placement
    {0x0200, 6, 0, 1},   // rate.wide
    {0x0201, 6, 0, 1},   // rate.wide
    {0x0203, 6, 0, 1},   // rate.wide
    {0x0204, 6, 0, 1},   // rate.wide
    {0x0206, 6, 0, 1},   // rate.wide
    {0x0207, 6, 0, 1},   // rate.wide
    {0x0208, 5, 1, 3},   // delay_time.time3
    {0x0209, 0, 1, 0},   // delay_time.pre_delay
    {0x0209, 5, 1, 3},   // delay_time.time3
    {0x020A, 1, 0, 1},   // rate.wide
    {0x0400, 12, 0, 0},  // rate.narrow
    {0x0400, 16, 1, 4},  // delay_time.time4
    {0x0401, 9, 3, 0},   // gain.tone
    {0x0401, 10, 2, 0},  // freq.eq
    {0x0401, 11, 5, 0},  // width.section
    {0x0401, 12, 3, 0},  // gain.tone
    {0x0401, 13, 3, 0},  // gain.tone
    {0x0403, 4, 3, 0},   // gain.tone
    {0x0403, 5, 2, 0},   // freq.eq
    {0x0403, 6, 5, 0},   // width.section
    {0x0403, 7, 3, 0},   // gain.tone
    {0x0403, 8, 3, 0},   // gain.tone
    {0x0403, 10, 0, 0},  // rate.narrow
    {0x0403, 16, 2, 2},  // freq.damping
    {0x0406, 15, 6, 0},  // wave.modulator
    {0x0500, 12, 0, 0},  // rate.narrow
    {0x1100, 0, 1, 0},   // delay_time.pre_delay
    {0x1100, 5, 1, 3},   // delay_time.time3
    {0x1101, 0, 1, 0},   // delay_time.pre_delay
    {0x1101, 5, 1, 3},   // delay_time.time3
    {0x1105, 6, 0, 1},   // rate.wide
}};

/// What every type powers up holding. `measured` is clear where a slot was refused.
inline constexpr int kGsEfxTypesWithCompleteDefaults = 62;
inline constexpr std::array<GsEfxTypeDefaults, 65> kGsEfxTypeDefaults = {{
    {0x0000, 0xFFFFF, {0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 127}},
    {0x0100, 0xFFFFF, {1, 69, 1, 52, 72, 0, 72, 56, 0, 56, 0, 0, 0, 0, 0, 0, 0, 0, 0, 127}},
    {0x0101, 0xFFFFF, {60, 65, 67, 70, 66, 63, 60, 59, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 127}},
    {0x0102, 0xFFFFF, {64, 127, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 67, 64, 0, 127}},
    {0x0103, 0xFFFFF, {48, 1, 0, 127, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 64, 64, 127}},
    {0x0110, 0xFFFFF, {48, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 64, 64, 96}},
    {0x0111, 0xFFFFF, {76, 3, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 56, 64, 84}},
    {0x0120, 0xFFFFF, {36, 16, 64, 16, 127, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 64, 0, 104}},
    {0x0121, 0xFFFFF, {1, 0, 68, 62, 40, 72, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 64, 64, 96}},
    {0x0122, 0xFFFFF, {6, 113, 24, 127, 17, 120, 88, 64, 96, 0, 0, 0, 0, 0, 0, 0, 64, 64, 0, 127}},
    {0x0123, 0xFFFFF, {0, 0, 16, 11, 24, 104, 90, 0, 0, 0, 0, 0, 0, 0, 0, 64, 64, 64, 0, 104}},
    {0x0124, 0xFFFFF, {10, 5, 95, 79, 90, 54, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 64, 64, 0, 96}},
    {0x0125, 0xFFFFF, {1, 60, 96, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 64, 0, 127}},
    {0x0126, 0xFFFFF, {1, 60, 96, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 64, 0, 127}},
    {0x0130, 0xFFFFF, {72, 100, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 64, 64, 104}},
    {0x0131, 0xFFFFF, {85, 3, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 64, 64, 127}},
    {0x0140, 0xFFFFF, {24, 8, 127, 5, 66, 16, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 64, 64, 0, 112}},
    {0x0141, 0xFFFFF, {16, 8, 40, 40, 60, 96, 0, 0, 0, 0, 0, 0, 0, 0, 0, 127, 64, 64, 0, 127}},
    {0x0142, 0xFFFFF, {0, 0, 10, 8, 111, 0, 90, 0, 0, 0, 0, 0, 0, 0, 0, 64, 64, 64, 0, 104}},
    {0x0143, 0xFFFFF, {32, 8, 127, 90, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 64, 64, 0, 96}},
    {0x0144, 0xFFFFF, {10, 8, 72, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 64, 64, 0, 80}},
    {0x0150, 0xFFFFF, {101, 116, 88, 1, 0, 0, 0, 127, 0, 0, 0, 0, 0, 0, 0, 48, 64, 64, 0, 127}},
    {0x0151, 0xFFFFB, {90, 108, 0, 1, 12, 21, 90, 127, 0, 0, 0, 0, 0, 0, 0, 40, 64, 64, 0, 127}},
    {0x0152, 0xFFFFF, {20, 0, 7, 80, 127, 127, 127, 127, 0, 0, 0, 0, 0, 0, 0, 48, 64, 64, 0, 127}},
    {0x0153, 0xFFFFF, {60, 20, 40, 0, 127, 127, 127, 127, 80, 127,
                       0,  0,  0,  0, 0,   48,  64,  64,  0,  127}},
    {0x0154, 0xFFFFF, {60, 80, 80, 127, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 48, 64, 64, 0, 127}},
    {0x0155, 0xFFFFF, {3, 112, 120, 104, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 64, 64, 0, 127}},
    {0x0156, 0xFFFFF, {0, 5, 12, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 42, 64, 61, 0, 112}},
    {0x0157, 0xFFFFF, {116, 106, 110, 80, 40, 64, 64, 127, 0, 0,
                       0,   0,   0,   0,  0,  48, 64, 64,  0, 127}},
    {0x0160, 0xFFFFF, {71, 62, 0, 127, 59, 66, 0, 0, 2, 64, 0, 0, 0, 0, 0, 48, 64, 64, 0, 95}},
    {0x0161, 0xFFFFF, {71, 64, 84, 95, 2, 64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 64, 64, 58, 0, 127}},
    {0x0170, 0xFFFFF, {64, 25, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 127}},
    {0x0171, 0xFFFFF, {64, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 127}},
    {0x0172, 0xFFFFF, {1, 5, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 127, 64, 64, 64, 127}},
    {0x0173, 0xFFFFF, {1, 1, 36, 0, 64, 1, 127, 0, 0, 127, 0, 0, 127, 0, 1, 127, 64, 64, 64, 127}},
    {0x0200, 0xFFFFF, {48, 64, 1, 0, 0, 10, 8, 72, 0, 64, 0, 0, 0, 0, 0, 0, 64, 64, 0, 80}},
    {0x0201, 0xFFFFF, {48, 64, 1, 0, 0, 16, 11, 40, 104, 32, 0, 0, 0, 0, 0, 0, 64, 64, 0, 80}},
    {0x0202, 0xFFFFF, {48, 64, 1, 0, 0, 111, 80, 127, 0, 48, 0, 0, 0, 0, 0, 0, 64, 64, 0, 80}},
    {0x0203, 0xFFFFF, {48, 64, 1, 0, 0, 10, 8, 72, 0, 64, 0, 0, 0, 0, 0, 0, 64, 64, 0, 72}},
    {0x0204, 0xFFFFF, {48, 64, 1, 0, 0, 11, 11, 24, 104, 32, 0, 0, 0, 0, 0, 0, 64, 64, 0, 72}},
    {0x0205, 0xFFFFF, {48, 64, 1, 0, 0, 111, 80, 127, 0, 48, 0, 0, 0, 0, 0, 0, 64, 64, 0, 72}},
    {0x0206, 0xFFFFF, {64, 127, 0, 0, 0, 64, 8, 101, 0, 64, 0, 0, 0, 0, 0, 0, 64, 64, 0, 80}},
    {0x0207, 0xFFFFF, {64, 127, 0, 0, 0, 16, 11, 24, 104, 48, 0, 0, 0, 0, 0, 0, 64, 64, 0, 96}},
    {0x0208, 0xFFFFF, {64, 127, 0, 0, 0, 111, 80, 127, 0, 48, 0, 0, 0, 0, 0, 0, 64, 64, 0, 88}},
    {0x0209, 0xFFFBF, {10, 9, 120, 0, 64, 111, 0, 127, 0, 48, 0, 0, 0, 0, 0, 0, 64, 64, 0, 127}},
    {0x020A, 0xFFFBF, {16, 11, 24, 104, 64, 111, 0, 127, 0, 48, 0, 0, 0, 0, 0, 0, 64, 64, 0, 127}},
    {0x020B, 0xFFFFF, {10, 8, 120, 0, 64, 16, 11, 24, 104, 64, 0, 0, 0, 0, 0, 0, 64, 64, 0, 112}},
    {0x0300, 0xFFFFF, {13,  1,  64,  72, 0,  64, 64, 6, 113, 24,
                       127, 17, 120, 88, 64, 96, 0,  0, 0,   96}},
    {0x0400, 0xFFFFF, {100, 80, 100, 1,  0,   80, 0,  1,  69, 74,
                       1,   0,  8,   30, 102, 40, 60, 34, 15, 110}},
    {0x0401, 0xFFFFF, {70, 127, 90, 1, 0, 80, 2, 1, 1, 76, 56, 2, 69, 54, 0, 8, 96, 102, 0, 80}},
    {0x0402, 0xFFFFF, {1, 60, 10, 1, 1, 80, 2, 1, 64, 64, 1, 0, 8, 0, 89, 50, 32, 64, 30, 88}},
    {0x0403, 0xFFFFF, {50, 127, 75, 1,   76, 0,  2,   69, 52, 0,
                       8,  40,  79, 100, 24, 40, 127, 30, 0,  95}},
    {0x0404, 0xFFFFF, {1, 55, 40, 29, 80, 1, 76, 72, 0, 64, 64, 0, 8, 20, 102, 100, 6, 15, 80, 76}},
    {0x0405, 0xFFFFF, {72, 100, 75, 1, 0, 48, 0, 0, 1, 66, 72, 1, 68, 64, 0, 5, 20, 102, 64, 76}},
    {0x0406, 0xFFFFF, {64, 64, 36,  16,  32, 16, 64, 0,  127, 10,
                       8,  64, 104, 127, 1,  2,  60, 64, 1,   127}},
    {0x0500, 0xFFFFF, {50, 20, 67, 0, 2, 69, 61, 71, 64, 0, 39, 36, 8, 90, 80, 75, 20, 64, 40, 96}},
    {0x1100, 0xFFFFF, {10, 8, 120, 0, 64, 111, 80,  127, 0,   40,
                       0,  0, 0,   0, 0,  0,   127, 127, 127, 96}},
    {0x1101, 0xFFFFF, {16, 11, 24, 104, 64, 111, 80,  127, 0,   48,
                       0,  0,  0,  0,   0,  0,   127, 127, 127, 96}},
    {0x1102, 0xFFFFF, {16, 8, 120, 0, 64, 16, 11,  24,  104, 64,
                       0,  0, 0,   0, 0,  0,  127, 127, 127, 88}},
    {0x1103, 0xFFFFF, {0, 48, 1, 1, 0, 1, 76, 3, 1, 0, 0, 0, 0, 0, 0, 0, 96, 127, 84, 127}},
    {0x1104, 0xFFFFF, {0,   48, 1,  1,  0, 6, 113, 24,  127, 17,
                       120, 88, 64, 96, 0, 0, 96,  127, 127, 127}},
    {0x1105, 0xFFFFF, {0, 48, 1, 1, 0, 36, 16, 64, 16, 127, 0, 0, 0, 0, 0, 0, 96, 127, 127, 127}},
    {0x1106, 0xFFFFF, {0, 48, 1, 1, 0, 1, 0, 68, 62, 40, 72, 1, 0, 0, 0, 0, 96, 127, 127, 127}},
    {0x1107, 0xFFFFF, {36,  16, 64, 16, 127, 6, 113, 24,  127, 17,
                       120, 88, 64, 96, 0,   0, 127, 127, 127, 127}},
    {0x1108, 0xFFFFF, {36, 16, 64, 16, 127, 1, 0,   68,  62,  40,
                       72, 1,  0,  0,  0,   0, 127, 127, 127, 127}},
}};

}  // namespace sonare::midi::synth
