/* The bank: every GM program and GS variation the library voices, whatever has
 * been rendered. The listening surface shows one voice; this shows where all of
 * them stand, which is the half of the work that is otherwise only visible to
 * whoever remembers what has been captured.
 *
 * Three bands, because one list of 188 rows answers only the question you were
 * already on. The masthead is the overview — totals and the distribution across
 * the six stages — the toolbar narrows, and the table lists beside an inspector
 * that holds what a row cannot: the coverage denominator, which dimensions sit
 * outside the reference spread and by how much, and the ladder in full.
 *
 * It reads `tools/voice-status.json`, which is committed and generated by
 * `tools/voicematch/status.py`. Opening a voice is handed back to the caller
 * rather than reached for here: this file is the bank and knows nothing about
 * the transport.
 */

'use strict';

import { $, el, state } from './state.js';
import { t } from './i18n.js';

/* Sixteen engines, three methods. What the eye is being asked here is "physical
 * model, FM, or neither" — sixteen hues would answer nothing, and the engine's
 * own name is on the row. */
const METHODS = { fm: 'fm', subtractive: 'classic', additive: 'classic' };

export const methodOf = (engine) => (engine ? (METHODS[engine] || 'physical') : 'classic');

const METHOD_PICKS = [
  ['', 'bank.any'],
  ['physical', 'bank.physical'],
  ['fm', 'bank.fm'],
  ['classic', 'bank.classic'],
];

const FILTER_PICKS = [
  ['oracle', 'bank.fHasOracle'],
  ['no-oracle', 'bank.fNeedsOracle'],
  ['unwritten', 'bank.fUnwritten'],
  ['page', 'bank.fRendered'],
];

/// The six rungs, whose wording is argued in `tools/voicematch/docs/status.md`.
const RUNGS = [0, 1, 2, 3, 4, 5];
const rungAt = (i) => (i / 5).toFixed(1);

export const stageIndex = (v) => Math.max(0, Math.min(5, Math.round(v.stage * 5)));
const stageColor = (i) => `var(--s${i})`;

const bank = {
  method: '',
  filter: '',
  stage: null,     // a rung index, or null for every rung
};

/// Read off the control rather than mirrored into `bank`: the select is the one
/// place the choice lives, and a mirror is a second place for it to be wrong.
const sortKey = () => $('bankSort').value || 'address';

let openVoiceFn = () => {};

const hasPage = (slug) => state.sets.some((s) => s.id === slug);

export async function loadBank() {
  if (state.bank.loaded) return;
  try {
    const got = await (await fetch('bank.json')).json();
    state.bank.voices = got.voices || [];
  } catch {
    state.bank.voices = [];
  }
  state.bank.loaded = true;
}

function bankMatches(v) {
  const find = $('bankFind').value.trim().toLowerCase();
  if (bank.method && methodOf(v.engine) !== bank.method) return false;
  if (bank.stage !== null && stageIndex(v) !== bank.stage) return false;
  if (bank.filter === 'oracle' && !v.capture) return false;
  if (bank.filter === 'no-oracle' && v.capture) return false;
  if (bank.filter === 'unwritten' && !(v.open_candidates || []).length) return false;
  if (bank.filter === 'page' && !hasPage(v.slug)) return false;
  if (find) {
    const hay = [v.name, v.engine, v.patch, v.slug, v.tone_class].join(' ').toLowerCase();
    if (!hay.includes(find)) return false;
  }
  return true;
}

const addressOf = (v) =>
  (v.kit ? `kit ${v.program}` : `${v.program}${v.bank ? `:${v.bank}` : ''}`);

/* ---- the small repeated readouts, shared with the listening surface ---- */

export const dotEl = (engine) => el('span', `dot ${methodOf(engine)}`);

export function stageBar(v) {
  const bar = el('span', 'bar');
  const filled = stageIndex(v);
  bar.style.setProperty('--sc', stageColor(filled));
  for (let i = 0; i < 5; i += 1) bar.append(el('span', i < filled ? 'seg on' : 'seg'));
  return bar;
}

/* What the ear has said about this voice, as one chip.
 *
 * Absent where nothing has been said, which is the state most of the bank is
 * in and is the point: a list of 180 voices whose every row claims a status
 * says nothing, and the four that have been listened to are what a session
 * starts from. */
export function heardChip(id) {
  const got = (state.fbIndex || {})[id];
  if (!got) return el('span', 'heard');
  const chip = el('span', 'heard on', String(got.n));
  if (got.worst === 'broken' || got.worst === 'wrong-instrument') chip.classList.add('bad');
  else if (got.worst === 'acceptable' || got.worst === 'off') chip.classList.add('mid');
  else if (got.worst === 'ok') chip.classList.add('good');
  const said = [t('pick.notes', { n: got.n })];
  if (got.worst) said.push(gradeWord(got.worst));
  if (got.prefer) said.push(t('pick.prefer', { n: got.prefer }));
  chip.title = said.join(' · ');
  return chip;
}

/* The two claims nothing on disk implies: that the residual was diagnosed, and
 * that somebody listened and said it is the instrument. They are what the top
 * of the ladder is gated on, and no voice in this bank carries the second — so
 * an empty column here is the bank's own answer rather than a missing readout. */
export function signoffChip(v) {
  const wrap = el('span', 'signoff');
  if (!v) return wrap;
  for (const which of ['structure', 'music']) {
    const claim = (v.axes || {})[which];
    const state_ = claim && claim.state;
    if (!state_) continue;
    const chip = el('span', 'sg', t(`pick.${which}`));
    if (state_ === 'current') chip.classList.add('good');
    else if (state_ === 'stale') chip.classList.add('bad');
    else chip.classList.add('mid');
    chip.title = `${t(`pick.${which}.long`)} — ${t(`pick.${state_}`)}`;
    wrap.append(chip);
  }
  return wrap;
}

const gradeWord = (name) => t(
  name === 'wrong-instrument' ? 'grade.wrongInstrument' : `grade.${name}`);

function stageEl(v) {
  const wrap = el('span', 'stage');
  wrap.append(stageBar(v), el('span', '', v.stage.toFixed(1)));
  wrap.title = `${t(`stage.${stageIndex(v)}`)} — ${v.next}`;
  return wrap;
}

/// A proportional bar over a set of voices. One count in six is 1 of 188, so the
/// segments carry a floor width and the countable numbers live in the chips.
function distBar(into, voices) {
  into.replaceChildren();
  const total = voices.length || 1;
  for (const i of RUNGS) {
    const n = voices.filter((v) => stageIndex(v) === i).length;
    if (!n) continue;
    const seg = el('span');
    seg.style.flex = `${n} 1 0`;
    seg.style.background = stageColor(i);
    seg.title = `${n} ${t(`stage.${i}`)} (${Math.round((n / total) * 100)}%)`;
    into.append(seg);
  }
}

/* ---- masthead ---- */

function figure(label, value, onClick, warn) {
  const b = el('button', `fig${onClick ? ' act' : ''}${warn ? ' warn' : ''}`);
  b.type = 'button';
  b.append(el('span', 'num', String(value)), el('span', 'lab', label));
  if (onClick) b.addEventListener('click', onClick);
  else b.disabled = true;
  return b;
}

function renderMasthead() {
  const vs = state.bank.voices;
  const withOracle = vs.filter((v) => v.capture).length;
  const unwritten = vs.reduce((n, v) => n + (v.open_candidates || []).length, 0);
  const pages = vs.filter((v) => hasPage(v.slug)).length;
  const pick = (name) => () => {
    bank.filter = bank.filter === name ? '' : name;
    renderBank();
  };

  $('bankFigures').replaceChildren(
    figure(t('bank.voices'), vs.length, null),
    figure(t('bank.withOracle'), withOracle, pick('oracle')),
    figure(t('bank.unwritten'), unwritten, unwritten ? pick('unwritten') : null, unwritten > 0),
    figure(t('bank.rendered'), pages, pages ? pick('page') : null),
  );

  distBar($('bankDist'), vs);

  const keys = $('bankStageKeys');
  keys.replaceChildren();
  for (const i of RUNGS) {
    const n = vs.filter((v) => stageIndex(v) === i).length;
    const b = el('button', 'skey');
    b.type = 'button';
    b.setAttribute('aria-pressed', String(bank.stage === i));
    b.title = `${rungAt(i)} — ${t(`stage.${i}.of`)}`;
    const dot = el('span', 'dot');
    dot.style.background = stageColor(i);
    b.append(dot, el('span', '', t(`stage.${i}`)), el('span', n ? 'n' : 'n z', String(n)));
    b.addEventListener('click', () => {
      bank.stage = bank.stage === i ? null : i;
      renderBank();
    });
    keys.append(b);
  }
}

/* ---- rows ---- */

function bankRow(v, index) {
  const row = el('div', 'bank-row');
  row.id = `v-${v.slug}`;
  row.setAttribute('role', 'option');
  row.setAttribute('aria-selected', 'false');
  row.addEventListener('click', () => { $('bankRows').focus(); selectRow(index); });
  row.addEventListener('dblclick', () => openVoice(v));

  const who = el('span', 'who', v.name);
  if (v.patch) who.append(el('span', 'patch', `  ${v.patch}`));

  const engine = el('span', 'engine');
  engine.append(dotEl(v.engine), el('span', '', v.engine || t('bank.notReported')));
  engine.title = v.engine ? `${methodOf(v.engine)} — ${v.tone_class}` : '';

  const oracle = el('span', `oracle${v.capture ? '' : ' absent'}`,
    v.capture || t('bank.noOracle'));

  const tail = el('span', 'bank-tail');
  const open = v.open_candidates || [];
  if (open.length) {
    const badge = el('span', 'badge warn', t('bank.nUnwritten', { n: open.length }));
    badge.title = open.join(', ');
    tail.append(badge);
  }
  // Only past the oracle step: below it every voice says the same sentence, and
  // 150 copies of it bury the four that say something.
  if (v.stage > 0.2 && v.stage < 1) tail.append(el('span', 'next', v.next));

  row.append(el('span', 'addr', addressOf(v)), who, engine, stageEl(v), oracle,
    // The same two readouts the palette carries, from the same functions: what
    // the ear has said about this voice, and the two claims the top of the
    // ladder is gated on.
    heardChip(v.slug), signoffChip(v), tail);
  return row;
}

const SORTS = {
  address: null,   // the generated order, which is already program order
  stage: (a, b) => b.stage - a.stage || a.program - b.program,
  name: (a, b) => a.name.localeCompare(b.name),
};

export function renderBank() {
  const rows = $('bankRows');
  rows.replaceChildren();
  if (!state.bank.voices.length) {
    rows.append(el('p', 'bank-empty', t('bank.notGenerated')));
    $('bankCount').textContent = '';
    $('bankFigures').replaceChildren();
    $('bankStageKeys').replaceChildren();
    state.bank.shown = [];
    state.bank.cursor = -1;
    renderInspect();
    return;
  }
  renderMasthead();
  markToolbar();

  const held = state.bank.shown[state.bank.cursor]
    ? state.bank.shown[state.bank.cursor].slug : null;
  const cmp = SORTS[sortKey()];
  state.bank.shown = state.bank.voices.filter(bankMatches);
  if (cmp) state.bank.shown = [...state.bank.shown].sort(cmp);

  // The GM families are the address order's own headings; under any other sort
  // they would be sixteen headings interleaved at random.
  const grouped = sortKey() === 'address';
  let group = null;
  state.bank.shown.forEach((v, i) => {
    if (grouped && v.group !== group) {
      group = v.group;
      const mine = state.bank.shown.filter((x) => x.group === group);
      const mini = el('span', 'mini');
      distBar(mini, mine);
      const h = el('h2', 'bank-group');
      h.append(el('span', '', group), el('span', 'n', String(mine.length)), mini);
      rows.append(h);
    }
    rows.append(bankRow(v, i));
  });
  if (!state.bank.shown.length) rows.append(el('p', 'bank-empty', t('bank.nothingMatches')));

  $('bankCount').textContent = `${state.bank.shown.length} / ${state.bank.voices.length}`;
  // The selection follows the voice rather than the row number: a filter change
  // that leaves it on screen should not move the inspector to whatever slid
  // into its place.
  const back = held ? state.bank.shown.findIndex((v) => v.slug === held) : -1;
  selectRow(back >= 0 ? back : (state.bank.shown.length ? 0 : -1), true);
}

function markToolbar() {
  for (const b of $('bankMethod').querySelectorAll('button')) {
    b.setAttribute('aria-pressed', String(b.dataset.method === bank.method));
  }
  for (const b of $('bankFilter').querySelectorAll('button')) {
    b.setAttribute('aria-pressed', String(b.dataset.filter === bank.filter));
  }
}

/// Move the cursor, which is also the selection: one row is focused, inspected
/// and openable, so there is never a question of which one an action lands on.
function selectRow(i, quiet) {
  state.bank.cursor = i;
  const rows = [...$('bankRows').querySelectorAll('.bank-row')];
  rows.forEach((r, at) => {
    const on = at === i;
    r.setAttribute('aria-selected', String(on));
    if (on) r.setAttribute('aria-current', 'true');
    else r.removeAttribute('aria-current');
  });
  const cur = rows[i];
  $('bankRows').setAttribute('aria-activedescendant', cur ? cur.id : '');
  if (cur && !quiet) cur.scrollIntoView({ block: 'nearest' });
  renderInspect();
}

function moveCursor(delta) {
  if (!state.bank.shown.length) return;
  const n = state.bank.shown.length;
  selectRow((state.bank.cursor + delta + n) % n);
}

function openVoice(v) {
  if (!v || !hasPage(v.slug)) return;
  openVoiceFn(v.slug);
}

/* ---- inspector ---- */

/* Always present, so selecting a row never resizes the table beside it, and it
 * holds the legend when nothing is selected rather than sitting blank. */

function fact(dl, term, value, aside, warn) {
  dl.append(el('dt', '', term));
  const dd = el('dd', warn ? 'warn' : '', value);
  if (aside) dd.append(el('span', 'aside', `  ${aside}`));
  dl.append(dd);
}

function methodLegend() {
  const legend = el('div', 'legend');
  for (const [m, key] of [['physical', 'bank.physical'], ['fm', 'bank.fm'],
    ['classic', 'bank.classic']]) {
    const row = el('div');
    row.append(el('span', `dot ${m}`), el('span', '', t(key)));
    legend.append(row);
  }
  return legend;
}

const keyHint = () => el('p', 'key-hint',
  `↑ ↓ ${t('keys.bankMove')}   enter ${t('keys.bankOpen')}   / ${t('keys.bankFind')}`);

function ladderEl(here) {
  const ladder = el('div', 'ladder');
  for (const i of RUNGS) {
    const cls = here === null ? 'rung done'
      : `rung${i === here ? ' here' : i < here ? ' done' : ''}`;
    const r = el('div', cls);
    r.append(el('span', 'mark', i === here ? '▸' : '·'),
      el('span', 'at', rungAt(i)), el('span', '', t(`stage.${i}`)));
    r.title = t(`stage.${i}.of`);
    ladder.append(r);
  }
  return ladder;
}

function inspectLegend(box) {
  box.append(el('span', 'lab', t('bank.ladder')), ladderEl(null),
    el('span', 'lab', t('bank.methodLegend')), methodLegend(),
    el('p', 'hint', t('bank.selectOne')), keyHint());
}

function inspectVoice(box, v) {
  box.append(el('h2', '', v.name));
  box.append(el('p', 'addr-line',
    [addressOf(v), v.patch, v.tone_class].filter(Boolean).join('  ·  ')));

  const engine = el('p', 'addr-line engine');
  engine.append(dotEl(v.engine),
    el('span', '', `${v.engine || t('bank.notReported')}  ·  ${methodOf(v.engine)}`));
  box.append(engine);

  const here = stageIndex(v);
  box.append(el('span', 'lab',
    t('bank.stageOf', { n: v.stage.toFixed(1), name: t(`stage.${here}`) })));
  // Names only, with the rung marked. The predicate is the tooltip, and the one
  // move that would raise it is spelled out below — six wrapped predicates here
  // would be the tallest thing in the panel and the least actionable.
  box.append(ladderEl(here));

  box.append(el('span', 'lab', t('bank.measurement')));
  const dl = el('dl', 'facts');
  const ax = v.axes || {};
  if (v.capture) {
    fact(dl, t('bank.oracle'), v.capture, t('bank.timbres', {
      timbres: ax.timbres, rows: ax.profile_rows,
      gate: ax.gate_state || t('bank.gateNotRecorded'),
    }));
  } else {
    fact(dl, t('bank.oracle'), t('bank.notCaptured'), '', true);
  }

  const cov = ax.coverage || {};
  if (cov.canonical) {
    const excused = cov.excused || [];
    fact(dl, t('bank.coverage'),
      t('bank.coverageOf', { gated: cov.gated, canonical: cov.canonical }),
      excused.length ? t('bank.excused', { n: excused.length, list: excused.join(', ') }) : '',
      !cov.complete);
    if ((cov.gaps || []).length) {
      fact(dl, t('bank.gaps'), String(cov.gaps.length), cov.gaps.join(', '), true);
    }
  }

  const ag = ax.agreement || {};
  if (ag.total) {
    const outside = Object.entries(ag.outside || {}).map(([d, m]) => `${d} ${m}×`);
    fact(dl, t('bank.agreement'),
      t('bank.agreementOf', { inside: ag.inside, total: ag.total }), outside.join(', '));
  } else if ((ag.unjudgeable || []).length) {
    fact(dl, t('bank.agreement'), t('bank.noSpread'),
      t('bank.unjudgeable', { n: ag.unjudgeable.length }), true);
  }

  const open = v.open_candidates || [];
  if (open.length) fact(dl, t('bank.unwritten'), String(open.length), open.join(', '), true);
  box.append(dl);

  box.append(el('span', 'lab', t('bank.next')), el('p', 'next-text', v.next));

  if (hasPage(v.slug)) {
    const go = el('button', 'go', t('bank.listen'));
    go.type = 'button';
    go.addEventListener('click', () => openVoice(v));
    box.append(go);
  }
  box.append(keyHint());
}

function renderInspect() {
  const box = $('bankInspect');
  box.replaceChildren();
  const v = state.bank.shown[state.bank.cursor];
  if (v) inspectVoice(box, v);
  else inspectLegend(box);
}

/* ---- keys and wiring ---- */

export function bankKey(ev) {
  const k = ev.key;
  if (k === '/') { ev.preventDefault(); $('bankFind').focus(); return; }
  if (k === 'ArrowDown' || k === 'j') { ev.preventDefault(); moveCursor(1); return; }
  if (k === 'ArrowUp' || k === 'k') { ev.preventDefault(); moveCursor(-1); return; }
  if (k === 'Home') { ev.preventDefault(); selectRow(0); return; }
  if (k === 'End') { ev.preventDefault(); selectRow(state.bank.shown.length - 1); return; }
  if (k === 'Enter') { ev.preventDefault(); openVoice(state.bank.shown[state.bank.cursor]); }
}

export function wireBank(onOpen) {
  openVoiceFn = onOpen;

  const method = $('bankMethod');
  method.replaceChildren();
  for (const [value, key] of METHOD_PICKS) {
    const b = el('button', '', t(key));
    b.type = 'button';
    b.dataset.method = value;
    b.addEventListener('click', () => { bank.method = value; renderBank(); });
    method.append(b);
  }

  const filter = $('bankFilter');
  filter.replaceChildren();
  for (const [value, key] of FILTER_PICKS) {
    const b = el('button', 'chip', t(key));
    b.type = 'button';
    b.dataset.filter = value;
    b.addEventListener('click', () => {
      bank.filter = bank.filter === value ? '' : value;
      renderBank();
    });
    filter.append(b);
  }
}

/// The toolbar is built in script, so a language change rebuilds it and the
/// table with it.
export function refreshBank() {
  wireBank(openVoiceFn);
  if (state.bank.loaded) renderBank();
}
