#!/usr/bin/env python3
"""Generate the image-source-method (ISM) golden fixture from pyroomacoustics.

This is the independent cross-engine oracle for the image-source code: the
arrival times (and per-image reflection products) computed by pyroomacoustics'
ISM, against which `sonare::acoustic::shoebox_image_sources` is checked
(arrival time within ±1 sample). pyroomacoustics is an optional dev dependency
and is NOT required for the normal build/test; the C++ comparison test SKIPs
when this fixture is absent.

Usage:
    pip install pyroomacoustics numpy
    python3 tests/fixtures/acoustic/room_sim/gen_ism_golden.py \
        > tests/fixtures/acoustic/room_sim/ism_golden.tsv

Output is a TSV: '#'-prefixed comment lines, scalar rows
(room/source/listener/sample_rate/max_order/absorption), then one
'image\t<distance_m>\t<reflection>' row per image source, sorted by distance.
"""

import sys

import numpy as np
import pyroomacoustics as pra

# Room and placement must match the C++ test (acoustic/ism_golden_test.cpp).
LENGTH, WIDTH, HEIGHT = 5.0, 4.0, 3.0
SOURCE = [1.0, 1.0, 1.0]
LISTENER = [2.0, 3.0, 2.0]
SAMPLE_RATE = 48000
MAX_ORDER = 2
ABSORPTION = 0.19  # uniform; beta = sqrt(1 - 0.19) = 0.9 per wall


def main() -> None:
    room = pra.ShoeBox(
        [LENGTH, WIDTH, HEIGHT],
        fs=SAMPLE_RATE,
        materials=pra.Material(ABSORPTION),
        max_order=MAX_ORDER,
    )
    room.add_source(SOURCE)
    room.add_microphone(np.array(LISTENER).reshape(3, 1))
    room.image_source_model()

    src = room.sources[0]
    images = src.images  # shape (3, n_images)
    listener = np.array(LISTENER).reshape(3, 1)
    distances = np.linalg.norm(images - listener, axis=0)
    # Per-image reflection product (broadband pressure damping).
    damping = src.damping.reshape(-1)

    rows = sorted(zip(distances.tolist(), damping.tolist()), key=lambda r: r[0])

    out = sys.stdout
    out.write("# ISM golden generated by pyroomacoustics. Do not edit by hand.\n")
    out.write(f"# pyroomacoustics {pra.__version__}\n")
    out.write(f"room\t{LENGTH}\t{WIDTH}\t{HEIGHT}\n")
    out.write(f"source\t{SOURCE[0]}\t{SOURCE[1]}\t{SOURCE[2]}\n")
    out.write(f"listener\t{LISTENER[0]}\t{LISTENER[1]}\t{LISTENER[2]}\n")
    out.write(f"sample_rate\t{SAMPLE_RATE}\n")
    out.write(f"max_order\t{MAX_ORDER}\n")
    out.write(f"absorption\t{ABSORPTION}\n")
    for dist, refl in rows:
        out.write(f"image\t{dist:.9f}\t{refl:.9f}\n")


if __name__ == "__main__":
    main()
