"""Render the hand-written insertion-effect bindings into a C++ header.

``tools/gs/efx-bindings/*.json`` says, for one (type, slot) of the GS
insertion-effect block, which insert control the byte drives and which
conversion law reads it. This turns the rows carrying a ``stage`` into a
table ``gs_layer.cpp`` walks, so a binding is a data row rather than a
branch someone remembered to write.

Only the two committed inputs are read -- the binding files and
``tools/gs/efx-tables.json``, the latter for the order its classes file
their tables in, which is the same order ``gs_efx_tables.h`` numbers them
in. The measurement archive is NOT needed: a clone can regenerate this
header, which is why it does not live in ``derive_efx_tables.py``.

Usage::

    bindings_header.py [--bindings tools/gs/efx-bindings]
                       [--tables tools/gs/efx-tables.json]
                       [--header src/midi/synth/gs_efx_bindings.h] [--check]
"""

from __future__ import annotations

import argparse
import importlib.util
import json
import subprocess
import sys
from pathlib import Path

GENERATED_BY = "tools/gs/bindings_header.py"


def class_order(derive_path: Path) -> tuple[str, ...]:
    """The class numbering ``gs_efx_tables.h`` emits, read from its own source.

    Imported rather than restated: a second copy of the order would put the
    two headers' class numbers silently out of step, and nothing downstream
    compares them.
    """
    spec = importlib.util.spec_from_file_location("derive_efx_tables", derive_path)
    if spec is None or spec.loader is None:
        sys.exit(f"could not load {derive_path}")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return tuple(module.CLASS_ORDER)


def load_rows(bindings_dir: Path) -> list[dict]:
    if not bindings_dir.is_dir():
        sys.exit(f"{bindings_dir} is not a directory")
    rows: list[dict] = []
    for path in sorted(bindings_dir.glob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        if not isinstance(data, list):
            sys.exit(f"{path} must hold a JSON list of binding rows")
        for index, row in enumerate(data):
            rows.append(dict(row, _file=path.name, _index=index))
    return rows


def parsed_type(text: str) -> int:
    msb, lsb = text.split()
    return (int(msb, 16) << 8) | int(lsb, 16)


def keys_of(row: dict) -> list[str]:
    """A row names one control or several; both spellings reach here as a list."""
    if "keys" in row:
        keys = row["keys"]
        if not isinstance(keys, list) or not keys:
            sys.exit(f'{row["_file"]}[{row["_index"]}]: "keys" must be a non-empty list')
        return [str(key) for key in keys]
    return [str(row["key"])]


def collect(rows: list[dict], classes: dict, order: tuple[str, ...]) -> list[dict]:
    """One emitted entry per (type, slot, key) a binding row translates."""
    out: list[dict] = []
    for row in rows:
        if "stage" not in row:
            continue
        where = f"{row['_file']}[{row['_index']}]"
        gs_class = row.get("class")
        table = row.get("table")
        if gs_class not in order:
            sys.exit(f"{where}: class {gs_class!r} is not one the tables declare")
        tables = list(classes[gs_class]["tables"])
        if table not in tables:
            sys.exit(f"{where}: {gs_class!r} has no table {table!r}")
        for key in keys_of(row):
            out.append(
                {
                    "type": parsed_type(row["type"]),
                    "slot": int(row["slot"]),
                    "conversion_class": order.index(gs_class),
                    "table": tables.index(table),
                    "stage": str(row["stage"]),
                    "key": key,
                    "label": f"{gs_class}.{table}",
                }
            )
    # Sorted so a type's rows are contiguous and the walk over one unit's
    # twenty slots visits them in slot order.
    out.sort(key=lambda entry: (entry["type"], entry["slot"], entry["key"]))
    duplicates = set()
    seen = set()
    for entry in out:
        address = (entry["type"], entry["slot"], entry["key"])
        if address in seen:
            duplicates.add(address)
        seen.add(address)
    if duplicates:
        spelled = ", ".join(
            f"{type_:#06x} slot {slot} {key}" for type_, slot, key in sorted(duplicates)
        )
        sys.exit(f"two binding rows drive the same control: {spelled}")
    return out


def render(entries: list[dict]) -> str:
    stages = sorted({entry["stage"] for entry in entries})
    keys = sorted({entry["key"] for entry in entries})
    out: list[str] = []
    w = out.append

    w(f"// Generated by {GENERATED_BY} from tools/gs/efx-bindings/ -- do not edit.")
    w("//")
    w("// Which insert control each insertion-effect parameter byte drives. One row")
    w("// per (type, slot, key) a binding file translates; the rows a binding file")
    w("// leaves as a documented state, as unmapped or as the skeleton's own")
    w("// business are absent, which is what makes a missing row mean something.")
    w("//")
    w("// The conversion law is named rather than carried: `conversion_class` and")
    w("// `table` index the same tables gs_efx_tables.h numbers, so a byte read")
    w("// here and a byte read through kGsEfxSlotConversions read alike.")
    w("")
    w("#pragma once")
    w("")
    w("#include <array>")
    w("#include <cstdint>")
    w("#include <string_view>")
    w("")
    w("namespace sonare::midi::synth {")
    w("")
    w("/// One insert control an insertion-effect byte drives.")
    w("struct GsEfxBinding {")
    w("  uint16_t type;             ///< The two type bytes, MSB in the high byte.")
    w("  uint8_t slot;              ///< Slot index from the first parameter address.")
    w("  uint8_t conversion_class;  ///< One of the kGsEfxClass* values.")
    w("  uint8_t table;             ///< Which table of that class.")
    w("  uint8_t stage;             ///< Index into kGsEfxBindingStages.")
    w("  uint8_t key;               ///< Index into kGsEfxBindingKeys.")
    w("};")
    w("")
    w("// The insert names and control names the rows below point at, each spelled")
    w("// once. A name is an index so the table stays a plain array of integers.")
    w(f"inline constexpr std::array<std::string_view, {len(stages)}> kGsEfxBindingStages = {{{{")
    for stage in stages:
        w(f'    "{stage}",')
    w("}};")
    w("")
    w(f"inline constexpr std::array<std::string_view, {len(keys)}> kGsEfxBindingKeys = {{{{")
    for key in keys:
        w(f'    "{key}",')
    w("}};")
    w("")
    w("// Sorted by (type, slot, key), so one unit's rows are contiguous.")
    w(f"inline constexpr std::array<GsEfxBinding, {len(entries)}> kGsEfxBindings = {{{{")
    stage_index = {name: i for i, name in enumerate(stages)}
    key_index = {name: i for i, name in enumerate(keys)}
    for entry in entries:
        w(
            f"    {{0x{entry['type']:04X}, {entry['slot']}, {entry['conversion_class']}, "
            f"{entry['table']}, {stage_index[entry['stage']]}, {key_index[entry['key']]}}},"
            f"  // {entry['label']} -> {entry['stage']}.{entry['key']}"
        )
    w("}};")
    w("")
    w("}  // namespace sonare::midi::synth")
    return "\n".join(out) + "\n"


def laid_out(text: str, header: Path) -> str:
    """The header as clang-format lays it out, which is how it is committed.

    The repository formats every header, so an unformatted rendering would
    differ from the committed one over layout alone and report as drift.
    Run here rather than raced with ``make format``, and with the style named
    explicitly: a style found by proximity would lay a scratch copy out
    differently from the committed one.
    """
    style = Path(__file__).resolve().parents[2] / ".clang-format"
    try:
        done = subprocess.run(
            ["clang-format", f"--style=file:{style}", f"--assume-filename={header}"],
            input=text,
            capture_output=True,
            text=True,
            check=True,
        )
    except (OSError, subprocess.CalledProcessError) as failure:
        sys.exit(f"clang-format could not lay out {header} ({failure})")
    return done.stdout


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--bindings", type=Path, default=Path("tools/gs/efx-bindings"))
    parser.add_argument("--tables", type=Path, default=Path("tools/gs/efx-tables.json"))
    parser.add_argument("--derive", type=Path, default=Path("tools/gs/derive_efx_tables.py"))
    parser.add_argument("--header", type=Path, default=Path("src/midi/synth/gs_efx_bindings.h"))
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when the header on disk differs from what these inputs render",
    )
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    order = class_order(args.derive)
    classes = json.loads(args.tables.read_text(encoding="utf-8"))["classes"]
    entries = collect(load_rows(args.bindings), classes, order)
    if not entries:
        sys.exit("no binding row carries a stage; the header would bind nothing")
    rendered = laid_out(render(entries), args.header)

    if args.check:
        try:
            current = args.header.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"binding header is missing: {args.header}", file=sys.stderr)
            return 1
        if current != rendered:
            print(
                f"binding header is stale: {args.header} (run make gs-efx-bindings)",
                file=sys.stderr,
            )
            return 1
        print(f"binding header is current: {args.header} ({len(entries)} controls)")
        return 0

    args.header.write_text(rendered, encoding="utf-8")
    print(f"wrote {args.header} ({len(entries)} controls)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
