#!/usr/bin/env python3
"""Renders the address census into a C++ header the coverage test includes.

The test needs the census in the same build as the address table, and the repo
prefers generated code over a parser: a JSON reader in the test would be a
second thing to keep right. `make gs-census-header` regenerates this; the
result is committed so a fresh clone runs the gate without a corpus.

Only the address and the file count survive the rendering. The counts, payload
lengths and value ranges stay in the JSON, where a human reads them.
"""

from __future__ import annotations

import argparse
import json


HEADER = """// Generated by tools/gs/gen_census_header.py -- do not edit.
//
// Every GS address observed in a corpus of real Standard MIDI Files, with the
// number of files that used it. The corpus is not in the repository; see
// tools/gs/docs/census.md.

#pragma once

#include <array>
#include <cstddef>
#include <cstdint>

namespace sonare::test {

struct GsCensusAddress {
  uint32_t addr;
  uint32_t files;  ///< Distinct corpus files that wrote this address.
};

/// %(source)s
/// %(files_scanned)d files scanned, %(files_with_gs)d carrying GS.
inline constexpr std::array<GsCensusAddress, %(count)d> kGsCensusAddresses = {{
"""

FOOTER = """}};

}  // namespace sonare::test
"""


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--census", required=True)
    parser.add_argument("--out", required=True)
    args = parser.parse_args()

    with open(args.census, encoding="utf-8") as handle:
        census = json.load(handle)

    columns = census["address_columns"]
    addr_at = columns.index("address")
    files_at = columns.index("files")

    rows = []
    for row in census["addresses"]:
        addr = int(row[addr_at].replace(" ", ""), 16)
        rows.append((addr, row[files_at]))
    rows.sort()

    with open(args.out, "w", encoding="utf-8") as handle:
        handle.write(
            HEADER
            % {
                "source": census["source"],
                "files_scanned": census["files_scanned"],
                "files_with_gs": census["files_with_gs"],
                "count": len(rows),
            }
        )
        for addr, files in rows:
            handle.write("    {0x%06X, %d},\n" % (addr, files))
        handle.write(FOOTER)

    print("%d addresses -> %s" % (len(rows), args.out))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
