"""Derive the horizontal HRTF ring of `stereo.binaural` from the shipped SHRF set.

`sonare_mastering` does not link `sonare_playback`, so the binaural panner
cannot read `src/playback/default.shrf` at run time. This tool reduces the set's
elevation-0 row to a small plain-data table that the panner includes instead:

  1. Mirror-average the row so the ring is exactly left/right symmetric: the
     right ear at azimuth a becomes the mean of the measured right ear at a and
     the measured left ear at -a, and the ITD becomes the odd part of the
     measured ITD. Only the right ear is stored; the left ear at a is the right
     ear at -a.
  2. Re-derive the minimum phase of each averaged response (the mean of two
     minimum-phase responses need not be one), truncate to `--taps`, and fade
     the tail with a half-Hann window.
  3. Scale the whole ring by one factor so the frontal response has unit gain
     at DC, where a head is acoustically transparent.
  4. Quantize to int16 with one scale for the ring.

`--check` regenerates in memory and fails if the committed table differs.
"""

from __future__ import annotations

import argparse
import struct
import sys
from pathlib import Path

import numpy as np

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_SOURCE = REPO_ROOT / "src/playback/default.shrf"
DEFAULT_OUTPUT = REPO_ROOT / "src/mastering/stereo/binaural_ring.inc"

_SHRF_MAGIC = b"SHRF"
_SHRF_HEADER_FORMAT = "<4sHBBIHHHHffff"
_SHRF_HEADER_BYTES = 36
_TAPER_TAPS = 16
_VALUES_PER_LINE = 12


def read_shrf(path: Path) -> tuple[dict, np.ndarray, np.ndarray]:
    """Header fields, the ITD table [el][az] and the HRIRs [el][az][ear][tap]."""
    raw = path.read_bytes()
    (
        magic,
        version,
        quant,
        _,
        sample_rate,
        taps,
        n_az,
        n_el,
        _,
        az_step,
        el_min,
        el_step,
        scale,
    ) = struct.unpack(_SHRF_HEADER_FORMAT, raw[:_SHRF_HEADER_BYTES])
    if magic != _SHRF_MAGIC or version != 1:
        raise ValueError(f"{path} is not SHRF v1")
    offset = _SHRF_HEADER_BYTES
    itd = np.frombuffer(raw, "<f4", n_el * n_az, offset).astype(np.float64).reshape(n_el, n_az)
    offset += n_el * n_az * 4
    count = n_el * n_az * 2 * taps
    if quant == 1:
        hrir = np.frombuffer(raw, "<i2", count, offset).astype(np.float64) * scale
    else:
        hrir = np.frombuffer(raw, "<f4", count, offset).astype(np.float64)
    header = {
        "sample_rate": sample_rate,
        "taps": taps,
        "n_az": n_az,
        "n_el": n_el,
        "az_step": az_step,
        "el_min": el_min,
        "el_step": el_step,
    }
    return header, itd, hrir.reshape(n_el, n_az, 2, taps)


def minimum_phase(h: np.ndarray) -> np.ndarray:
    """Minimum-phase reconstruction of `h` via the real cepstrum, same length."""
    n_fft = 1
    while n_fft < 8 * len(h):
        n_fft *= 2
    log_mag = np.log(np.maximum(np.abs(np.fft.rfft(h, n_fft)), 1e-10))
    cepstrum = np.fft.irfft(log_mag, n_fft)
    fold = np.zeros(n_fft)
    fold[0] = 1.0
    fold[1 : n_fft // 2] = 2.0
    fold[n_fft // 2] = 1.0
    return np.fft.irfft(np.exp(np.fft.rfft(cepstrum * fold, n_fft)), n_fft)[: len(h)]


def build_ring(source: Path, taps: int) -> tuple[int, float, np.ndarray, np.ndarray, float]:
    """(sample rate, azimuth step, int16 right-ear ring, half ITD table, int16 scale)."""
    header, itd, hrir = read_shrf(source)
    row = round((0.0 - header["el_min"]) / header["el_step"])
    if not 0 <= row < header["n_el"]:
        raise ValueError("the set has no elevation-0 row")
    n_az = header["n_az"]
    if n_az % 2 != 0:
        raise ValueError("a mirrored ring needs an even azimuth count")
    mirror = (-np.arange(n_az)) % n_az
    left = hrir[row, :, 0, :]
    right = hrir[row, :, 1, :]
    averaged = 0.5 * (right + left[mirror])
    ring = np.empty((n_az, taps))
    fade = np.hanning(2 * _TAPER_TAPS)[_TAPER_TAPS:]
    for az in range(n_az):
        response = minimum_phase(averaged[az])[:taps].copy()
        response[-_TAPER_TAPS:] *= fade
        ring[az] = response
    ring /= float(np.sum(ring[0]))
    itd_half = 0.5 * (itd[row] - itd[row][mirror])[: n_az // 2 + 1]
    peak = float(np.max(np.abs(ring)))
    scale = peak / 32767.0
    quantized = np.clip(np.round(ring / scale), -32768, 32767).astype(np.int16)
    return header["sample_rate"], float(header["az_step"]), quantized, itd_half, scale


def render(source: Path, taps: int) -> str:
    sample_rate, az_step, ring, itd_half, scale = build_ring(source, taps)
    n_az = ring.shape[0]
    lines = [
        "// Generated by tools/playback/shrf_ring_header.py -- do not edit.",
        "//",
        "// Horizontal HRTF ring of stereo.binaural, derived from the elevation-0 row",
        "// of src/playback/default.shrf (SADIE II subject D1, Apache-2.0; see NOTICE):",
        "// mirror-averaged, minimum phase, unit frontal gain at DC. Plain data with no",
        "// includes; the includer supplies <cstdint> and the namespace.",
        "",
        f"constexpr int kRingSampleRate = {sample_rate};",
        f"constexpr int kRingTaps = {taps};",
        f"constexpr int kRingAzimuths = {n_az};",
        f"constexpr float kRingAzimuthStepDeg = {az_step:.1f}f;",
        "// A stored sample times this scale is the response value.",
        f"constexpr float kRingScale = {scale:.9e}f;",
        "",
        "// Right-ear minimum-phase response at azimuth index a (a * step degrees,",
        "// positive to the right). The left ear at a is the right ear at (N - a) % N.",
        f"constexpr int16_t kRingHrir[{n_az}][{taps}] = {{",
    ]
    for az in range(n_az):
        lines.append("    {")
        values = [str(int(v)) for v in ring[az]]
        for start in range(0, len(values), _VALUES_PER_LINE):
            lines.append("        " + ", ".join(values[start : start + _VALUES_PER_LINE]) + ",")
        lines.append("    },")
    lines.append("};")
    lines.append("")
    lines.append("// ITD in samples at kRingSampleRate for azimuth index 0 .. N/2 (front to")
    lines.append("// back through the right); positive: the left ear lags. Odd in azimuth.")
    lines.append(f"constexpr float kRingItdSamples[{len(itd_half)}] = {{")
    values = [f"{v:.4f}f" for v in itd_half]
    for start in range(0, len(values), 8):
        lines.append("    " + ", ".join(values[start : start + 8]) + ",")
    lines.append("};")
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--source", type=Path, default=DEFAULT_SOURCE)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--taps", type=int, default=64)
    parser.add_argument(
        "--check", action="store_true", help="fail instead of rewriting a stale output"
    )
    args = parser.parse_args()
    text = render(args.source, args.taps)
    if args.check:
        if not args.output.exists() or args.output.read_text() != text:
            print(
                f"binaural ring is stale: {args.output} (run {Path(__file__).name})",
                file=sys.stderr,
            )
            return 1
        print(f"binaural ring is current: {args.output}")
        return 0
    args.output.write_text(text)
    print(f"wrote {args.output}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
