export {
  decomposeNotePitch,
  extractNotes,
  extractPercussiveEvents,
  harmonic,
  hpss,
  mergeNotes,
  normalize,
  noteMove,
  noteStretch,
  percussive,
  pitchCorrectTimevarying,
  pitchCorrectToMidi,
  pitchCorrectToMidiTimevarying,
  pitchShift,
  renderNotes,
  renderPercussiveEvents,
  spectralEdit,
  splitNote,
  timeStretch,
} from './effects_transform';
export type {
  VoiceChangeOptions,
  VoiceChangeRealtimeOptions,
  VoiceChangeRealtimeRequest,
  VoiceChangeRequest,
} from './effects_voice_change';
export { voiceChange, voiceChangeRealtime } from './effects_voice_change';
export {
  masterAudio,
  masterAudioStereo,
  masterAudioStereoWithProgress,
  masterAudioWithProgress,
  masteringChain,
  masteringChainStereo,
  masteringChainStereoWithProgress,
  masteringChainWithProgress,
  masteringPlatformNames,
  masteringPresetNames,
} from './mastering_chain';
export type {
  MasteringAbMatchLoudnessRequest,
  MasteringAssistantParamsRequest,
  MasteringAssistantStereoParamsRequest,
  MasteringChannelPolicy,
  MasteringInsertParamInfo,
  MasteringPairAnalyzeRequest,
  MasteringPairProcessRequest,
  MasteringProcessorCatalogEntry,
  MasteringProcessorCategory,
  MasteringProcessRequest,
  MasteringProcessStereoRequest,
  MasteringRealtimeCost,
  MasteringSamplesParamsRequest,
  MasteringStereoAnalyzeRequest,
  MasteringStereoParamsRequest,
  MasteringStreamingPreviewRequest,
  MasteringStreamingPreviewStereoRequest,
} from './mastering_core';
export {
  mastering,
  masteringAbMatchLoudness,
  masteringAssistantSuggest,
  masteringAssistantSuggestStereo,
  masteringAudioProfile,
  masteringAudioProfileStereo,
  masteringInsertNames,
  masteringInsertParamInfo,
  masteringInsertParamNames,
  masteringPairAnalysisNames,
  masteringPairAnalyze,
  masteringPairProcess,
  masteringPairProcessorNames,
  masteringProcess,
  masteringProcessorCatalog,
  masteringProcessorNames,
  masteringProcessStereo,
  masteringStereoAnalysisNames,
  masteringStereoAnalyze,
  masteringStreamingPreview,
  masteringStreamingPreviewStereo,
} from './mastering_core';
export type {
  CompressorDetector,
  CompressorOptions,
  DynamicsProcessorResult,
  GateOptions,
  MasteringDynamicsCompressorRequest,
  MasteringDynamicsGateRequest,
  MasteringDynamicsTransientShaperRequest,
  TransientShaperOptions,
} from './mastering_dynamics';
export {
  masteringDynamicsCompressor,
  masteringDynamicsGate,
  masteringDynamicsTransientShaper,
} from './mastering_dynamics';
export type { MixStereoRequest } from './mixing_oneshot';
export { mixingScenePresetJson, mixingScenePresetNames, mixStereo } from './mixing_oneshot';
export type {
  DereverbClassicalOptions,
  MasteringRepairDereverbClassicalLinkedRequest,
  MasteringRepairDereverbClassicalRequest,
  MasteringRepairDereverbClassicalStereoRequest,
  MasteringRepairDereverbConfigForRoomRequest,
  MasteringRepairDetectReverbRequest,
} from './repair_dereverb';
export {
  masteringRepairDereverbClassical,
  masteringRepairDereverbClassicalLinked,
  masteringRepairDereverbClassicalStereo,
  masteringRepairDereverbConfigForRoom,
  masteringRepairDetectReverb,
} from './repair_dereverb';
export type {
  DeclickOptions,
  DeclipOptions,
  DecrackleMode,
  DecrackleOptions,
  MasteringRepairDeclickRequest,
  MasteringRepairDeclickStereoRequest,
  MasteringRepairDeclipRequest,
  MasteringRepairDeclipStereoRequest,
  MasteringRepairDecrackleRequest,
  MasteringRepairDecrackleStereoRequest,
  MasteringRepairDetectClicksRequest,
  MasteringRepairDetectClippingRequest,
  MasteringRepairDetectCrackleRequest,
} from './repair_impulsive';
export {
  masteringRepairDeclick,
  masteringRepairDeclickStereo,
  masteringRepairDeclip,
  masteringRepairDeclipStereo,
  masteringRepairDecrackle,
  masteringRepairDecrackleStereo,
  masteringRepairDetectClicks,
  masteringRepairDetectClipping,
  masteringRepairDetectCrackle,
} from './repair_impulsive';
export type {
  DehumMode,
  DehumOptions,
  DenoiseClassicalMode,
  DenoiseClassicalNoiseEstimator,
  DenoiseClassicalOptions,
  MasteringRepairDehumRequest,
  MasteringRepairDehumStereoRequest,
  MasteringRepairDenoiseClassicalLinkedRequest,
  MasteringRepairDenoiseClassicalRequest,
  MasteringRepairDenoiseClassicalStereoRequest,
  MasteringRepairDetectHumRequest,
  MasteringRepairDetectNoiseFloorRequest,
  MasteringRepairNoiseBandBinsRequest,
} from './repair_noise';
export {
  masteringRepairDehum,
  masteringRepairDehumStereo,
  masteringRepairDenoiseClassical,
  masteringRepairDenoiseClassicalLinked,
  masteringRepairDenoiseClassicalStereo,
  masteringRepairDetectHum,
  masteringRepairDetectNoiseFloor,
  masteringRepairNoiseBandBins,
} from './repair_noise';
export type {
  MasteringRepairDetectTrimRangeRequest,
  MasteringRepairDetectTrimRangeStereoRequest,
  MasteringRepairTrimSilenceRequest,
  MasteringRepairTrimSilenceStereoRequest,
  TrimSilenceMode,
  TrimSilenceOptions,
} from './repair_trim';
export {
  masteringRepairDetectTrimRange,
  masteringRepairDetectTrimRangeStereo,
  masteringRepairTrimSilence,
  masteringRepairTrimSilenceStereo,
} from './repair_trim';
