#!/usr/bin/env python3
"""Generate the authoritative C-ABI struct layout snapshot.

This is the producer side of the ctypes struct-layout guard. The C++ core
protects its own structs with ~260 ``static_assert(sizeof(...))`` guards, but the
hand-written Python ctypes mirror has no such compile-time protection: a field
added, removed, reordered, or retyped on the C side silently desyncs it, which
surfaces as an import-time segfault rather than a clean failure.

ctypes is the only surface with a raw byte-for-byte struct mirror -- the Node
N-API and WASM (embind ``val``) bindings marshal structs field-by-field through
the C ABI into JS/native objects, so they have no byte layout to guard and
cannot segfault from layout drift (their field-name fidelity is covered by
parity + the ``.d.ts`` type files + golden tests). This guard therefore targets
ctypes specifically.

This tool closes that gap for the *layout* dimension only (it does NOT model
marshalling or behaviour, so it does not repeat the rolled-back codegen
experiment). It works in three steps:

1. Use the Python ctypes binding as the *registry* of structs we care about:
   every ``ctypes.Structure`` subclass across the ``_ffi_types_*`` modules names
   a struct and its field order. The ctypes modules import cleanly without the
   native library (they only ``import ctypes``), so this needs no build of the
   dylib.
2. Emit a tiny C++ probe that, for each registered struct, reports the
   *authoritative* layout straight from the C headers via ``sizeof`` /
   ``alignof`` / ``offsetof``. The C compiler is the oracle: if ctypes names a
   struct or field the C ABI does not have, the probe fails to compile -- which
   is itself the drift signal.
3. Run the probe and write a stable, sorted JSON snapshot to
   ``tools/abi/abi-layout.json``.

The snapshot is consumed by ``bindings/python/tests/test_abi_layout.py`` (byte
offsets vs ctypes reflection). Regenerate with ``make abi-layout``; the JSON is
tracked, so a layout change shows up as a reviewable git diff.
"""

from __future__ import annotations

import argparse
import ctypes
import importlib
import json
import os
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
PY_SRC = REPO_ROOT / "bindings" / "python" / "src"
DEFAULT_OUTPUT = REPO_ROOT / "tools" / "abi" / "abi-layout.json"

# ctypes modules that declare the mirror structs. Pure-Python (only `import
# ctypes`), so importing them never dlopen()s the native library.
FFI_MODULES = (
    "libsonare._ffi_types_core",
    "libsonare._ffi_types_analysis",
    "libsonare._ffi_types_mastering_project",
    "libsonare._ffi_types_repair",
    "libsonare._ffi_types_streaming",
)

# Headers the probe includes. sonare/sonare_c.h transitively pulls in the
# acoustic / effects / features / mastering / metering / mixing / project /
# streaming / types public headers (under include/sonare/); the helpers header
# is an internal C-API header under src/c_api/.
PROBE_HEADERS = ("sonare/sonare_c.h", "c_api/sonare_c_mastering_helpers.h")

# ctypes Structure subclasses that intentionally do NOT correspond to a public C
# typedef of the same name (binding-internal helpers). Excluded from the probe.
EXCLUDED_STRUCTS: frozenset[str] = frozenset()


def collect_structs() -> dict[str, list[str]]:
    """Map each mirrored struct name to its ordered ctypes field names.

    Re-exports (the same class imported into several modules) collapse to one
    entry. Two *different* classes sharing a name is a hard error.
    """
    sys.path.insert(0, str(PY_SRC))
    seen: dict[str, type[ctypes.Structure]] = {}
    fields: dict[str, list[str]] = {}
    for mod_name in FFI_MODULES:
        module = importlib.import_module(mod_name)
        for attr in vars(module).values():
            if not (
                isinstance(attr, type)
                and issubclass(attr, ctypes.Structure)
                and attr is not ctypes.Structure
            ):
                continue
            name = attr.__name__
            if name in EXCLUDED_STRUCTS:
                continue
            if not getattr(attr, "_fields_", None):
                continue
            prev = seen.get(name)
            if prev is not None:
                if prev is not attr:
                    raise SystemExit(f"two distinct ctypes Structures named {name!r}")
                continue
            seen[name] = attr
            fields[name] = [field_name for field_name, *_ in attr._fields_]
    if not fields:
        raise SystemExit("no ctypes Structure mirrors found")
    return dict(sorted(fields.items()))


def emit_probe(structs: dict[str, list[str]]) -> str:
    """Render the C++ probe that prints the authoritative layout as JSON."""
    lines = [
        "// Generated by tools/abi/gen_abi_layout.py -- do not edit.",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <cstdio>",
        "",
    ]
    lines += [f'#include "{header}"' for header in PROBE_HEADERS]
    lines += [
        "",
        "int main() {",
        '  std::printf("{\\n");',
    ]
    struct_items = list(structs.items())
    for s_idx, (struct, field_names) in enumerate(struct_items):
        struct_sep = "" if s_idx == len(struct_items) - 1 else ","
        lines.append(
            f'  std::printf("  \\"{struct}\\": {{\\"size\\": %zu, '
            f'\\"align\\": %zu, \\"fields\\": [\\n", '
            f"sizeof({struct}), alignof({struct}));"
        )
        for f_idx, field in enumerate(field_names):
            field_sep = "" if f_idx == len(field_names) - 1 else ","
            lines.append(
                f'  std::printf("    {{\\"name\\": \\"{field}\\", '
                f'\\"offset\\": %zu, \\"size\\": %zu}}{field_sep}\\n", '
                f"offsetof({struct}, {field}), "
                f"sizeof(((({struct}*)0)->{field})));"
            )
        lines.append(f'  std::printf("  ]}}{struct_sep}\\n");')
    lines += [
        '  std::printf("}\\n");',
        "  return 0;",
        "}",
        "",
    ]
    return "\n".join(lines)


def build_and_run(probe_src: str, cxx: str) -> dict:
    """Compile and run the probe, returning the parsed layout dict."""
    with tempfile.TemporaryDirectory() as tmp:
        tmp_dir = Path(tmp)
        src_path = tmp_dir / "abi_layout_probe.cpp"
        bin_path = tmp_dir / "abi_layout_probe"
        src_path.write_text(probe_src)
        compile_cmd = [
            cxx,
            "-std=c++17",
            "-I",
            str(REPO_ROOT / "include"),
            "-I",
            str(REPO_ROOT / "src"),
            str(src_path),
            "-o",
            str(bin_path),
        ]
        subprocess.run(compile_cmd, check=True, cwd=REPO_ROOT)
        result = subprocess.run([str(bin_path)], check=True, capture_output=True, text=True)
    return json.loads(result.stdout)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--output",
        type=Path,
        default=DEFAULT_OUTPUT,
        help="path to write the layout JSON (default: tools/abi/abi-layout.json)",
    )
    parser.add_argument(
        "--cxx",
        default=os.environ.get("CXX", "c++"),
        help="C++ compiler to use (default: $CXX or c++)",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the regenerated JSON differs from the committed file",
    )
    args = parser.parse_args()

    if shutil.which(args.cxx) is None and not Path(args.cxx).exists():
        raise SystemExit(f"C++ compiler not found: {args.cxx!r}")

    structs = collect_structs()
    layout = build_and_run(emit_probe(structs), args.cxx)
    rendered = json.dumps(layout, indent=2, sort_keys=True) + "\n"

    if args.check:
        current = args.output.read_text() if args.output.exists() else ""
        if current != rendered:
            sys.stderr.write(f"{args.output} is stale; run `make abi-layout` and commit.\n")
            return 1
        return 0

    args.output.write_text(rendered)
    sys.stderr.write(f"wrote {len(structs)} struct layouts to {args.output}\n")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
