"""libsonare - audio analysis library (Python binding)."""

from importlib.metadata import PackageNotFoundError
from importlib.metadata import version as _pkg_version

from .analyzer import (
    analyze,
    analyze_bpm,
    analyze_dynamics,
    analyze_rhythm,
    analyze_timbre,
    analyze_tts_quality,
    chroma,
    compress_pauses,
    detect_beats,
    detect_bpm,
    detect_chords,
    detect_key,
    detect_onsets,
    frames_to_time,
    harmonic,
    has_ffmpeg_support,
    hpss,
    hz_to_mel,
    hz_to_midi,
    hz_to_note,
    mastering,
    mastering_pair_analysis_names,
    mastering_pair_analyze,
    mastering_pair_process,
    mastering_pair_processor_names,
    mastering_process,
    mastering_process_stereo,
    mastering_processor_names,
    mastering_stereo_analysis_names,
    mastering_stereo_analyze,
    mel_spectrogram,
    mel_to_hz,
    mfcc,
    midi_to_hz,
    normalize,
    note_to_hz,
    percussive,
    pitch_pyin,
    pitch_shift,
    pitch_yin,
    prepare_tts,
    resample,
    rms_energy,
    spectral_bandwidth,
    spectral_centroid,
    spectral_flatness,
    spectral_rolloff,
    stft,
    stft_db,
    time_stretch,
    time_to_frames,
    trim,
    version,
    zero_crossing_rate,
)
from .audio import Audio
from .types import (
    AnalysisResult,
    BpmAnalysisResult,
    BpmCandidate,
    Chord,
    ChordAnalysisResult,
    ChromaResult,
    DynamicsResult,
    HpssResult,
    Key,
    MasteringResult,
    MasteringStereoResult,
    MelSpectrogramResult,
    MfccResult,
    Mode,
    PitchClass,
    PitchResult,
    RhythmResult,
    StftResult,
    TimbreResult,
    TimeSignature,
    TtsQualityResult,
)

try:
    __version__ = _pkg_version("libsonare")
except PackageNotFoundError:
    # Source checkout / editable install without metadata: fall back to the
    # native library's version string so ``libsonare.__version__`` is always
    # populated.
    __version__ = version()

__all__ = [
    "AnalysisResult",
    "Audio",
    "BpmAnalysisResult",
    "BpmCandidate",
    "Chord",
    "ChordAnalysisResult",
    "__version__",
    "ChromaResult",
    "DynamicsResult",
    "HpssResult",
    "Key",
    "MasteringResult",
    "MasteringStereoResult",
    "MelSpectrogramResult",
    "MfccResult",
    "Mode",
    "PitchClass",
    "PitchResult",
    "RhythmResult",
    "StftResult",
    "TimbreResult",
    "TimeSignature",
    "TtsQualityResult",
    "analyze",
    "analyze_bpm",
    "analyze_dynamics",
    "analyze_rhythm",
    "analyze_timbre",
    "analyze_tts_quality",
    "chroma",
    "compress_pauses",
    "detect_beats",
    "detect_bpm",
    "detect_chords",
    "detect_key",
    "detect_onsets",
    "frames_to_time",
    "harmonic",
    "has_ffmpeg_support",
    "hpss",
    "hz_to_mel",
    "hz_to_midi",
    "hz_to_note",
    "mel_spectrogram",
    "mel_to_hz",
    "mastering",
    "mastering_pair_analysis_names",
    "mastering_pair_analyze",
    "mastering_pair_process",
    "mastering_pair_processor_names",
    "mastering_process",
    "mastering_process_stereo",
    "mastering_processor_names",
    "mastering_stereo_analysis_names",
    "mastering_stereo_analyze",
    "mfcc",
    "midi_to_hz",
    "normalize",
    "note_to_hz",
    "percussive",
    "pitch_pyin",
    "pitch_shift",
    "pitch_yin",
    "prepare_tts",
    "resample",
    "rms_energy",
    "spectral_bandwidth",
    "spectral_centroid",
    "spectral_flatness",
    "spectral_rolloff",
    "stft",
    "stft_db",
    "time_stretch",
    "time_to_frames",
    "trim",
    "version",
    "zero_crossing_rate",
]
