from __future__ import annotations

from collections.abc import Sequence

from .types import (
    AutomationPoint,
    EngineBounceOptions,
    EngineBounceResult,
    EngineCaptureStatus,
    EngineClip,
    EngineFreezeOptions,
    EngineFreezeResult,
    EngineGraphSpec,
    EngineMarker,
    EngineMetronomeConfig,
    EngineTelemetry,
    ParameterInfo,
)

EXPECTED_ENGINE_ABI_VERSION: int

class RealtimeEngine:
    def __init__(
        self,
        sample_rate: float = 48000.0,
        max_block_size: int = 128,
        *,
        command_capacity: int = 1024,
        telemetry_capacity: int = 1024,
    ) -> None: ...
    def close(self) -> None: ...
    def __enter__(self) -> RealtimeEngine: ...
    def __exit__(self, *_exc: object) -> None: ...
    def prepare(
        self,
        sample_rate: float,
        max_block_size: int,
        command_capacity: int = 1024,
        telemetry_capacity: int = 1024,
    ) -> None: ...
    def play(self, render_frame: int = -1) -> None: ...
    def stop(self, render_frame: int = -1) -> None: ...
    def seek_sample(self, timeline_sample: int, render_frame: int = -1) -> None: ...
    def seek_ppq(self, ppq: float, render_frame: int = -1) -> None: ...
    def set_tempo(self, bpm: float) -> None: ...
    def set_time_signature(self, numerator: int, denominator: int) -> None: ...
    def set_loop(self, start_ppq: float, end_ppq: float, enabled: bool = True) -> None: ...
    def add_parameter(self, info: ParameterInfo) -> None: ...
    def parameter_count(self) -> int: ...
    def parameter_info_by_index(self, index: int) -> ParameterInfo: ...
    def parameter_info(self, id: int) -> ParameterInfo: ...
    def set_automation_lane(self, param_id: int, points: Sequence[AutomationPoint]) -> None: ...
    def automation_lane_count(self) -> int: ...
    def set_markers(self, markers: Sequence[EngineMarker]) -> None: ...
    def marker_count(self) -> int: ...
    def marker_by_index(self, index: int) -> EngineMarker: ...
    def marker(self, id: int) -> EngineMarker: ...
    def seek_marker(self, marker_id: int, render_frame: int = -1) -> None: ...
    def set_loop_from_markers(self, start_marker_id: int, end_marker_id: int) -> None: ...
    def set_metronome(self, config: EngineMetronomeConfig) -> None: ...
    def metronome(self) -> EngineMetronomeConfig: ...
    def count_in_end_sample(self, start_sample: int, bars: int) -> int: ...
    def set_clips(self, clips: Sequence[EngineClip]) -> None: ...
    def clip_count(self) -> int: ...
    def set_capture_buffer(self, num_channels: int, capacity_frames: int) -> None: ...
    def arm_capture(self, armed: bool = True) -> None: ...
    def set_capture_punch(
        self, start_sample: int, end_sample: int, enabled: bool = True
    ) -> None: ...
    def reset_capture(self) -> None: ...
    def capture_status(self) -> EngineCaptureStatus: ...
    def captured_audio(self) -> list[list[float]]: ...
    def set_graph(self, spec: EngineGraphSpec) -> None: ...
    def graph_node_count(self) -> int: ...
    def graph_connection_count(self) -> int: ...
    def process(self, channels: Sequence[Sequence[float]]) -> list[list[float]]: ...
    def render_offline(
        self, channels: Sequence[Sequence[float]], *, block_size: int = 128
    ) -> list[list[float]]: ...
    def bounce_offline(self, options: EngineBounceOptions) -> EngineBounceResult: ...
    def freeze_offline(self, options: EngineFreezeOptions) -> EngineFreezeResult: ...
    def drain_telemetry(self, max_records: int = 1024) -> list[EngineTelemetry]: ...
