from __future__ import annotations

import os
from collections.abc import Mapping, Sequence

from ._project import BuiltinSynthConfig, Sf2InstrumentConfig, SynthPatch
from .types import (
    AutomationPoint,
    ClipPageRequest,
    EngineBounceOptions,
    EngineBounceResult,
    EngineCaptureStatus,
    EngineClip,
    EngineFreezeOptions,
    EngineFreezeResult,
    EngineGraphSpec,
    EngineMarker,
    EngineMetronomeConfig,
    EngineMidiClipSchedule,
    EngineTelemetry,
    MeterTelemetryRecord,
    ParameterInfo,
    TransportState,
)

EXPECTED_ENGINE_ABI_VERSION: int

class ClipPageProvider:
    def __init__(self, num_channels: int, num_samples: int, page_frames: int) -> None: ...
    def close(self) -> None: ...
    def destroy(self) -> None: ...
    def __enter__(self) -> ClipPageProvider: ...
    def __exit__(self, *_exc: object) -> None: ...
    def supply(self, page_index: int, channels: Sequence[Sequence[float]]) -> None: ...
    def clear(self, page_index: int) -> None: ...

class FileClipPageProvider(ClipPageProvider):
    num_channels: int
    num_samples: int
    page_frames: int
    data_offset_bytes: int
    def __init__(
        self,
        path: str | os.PathLike[str],
        *,
        num_channels: int,
        num_samples: int,
        page_frames: int,
        data_offset_bytes: int = 0,
    ) -> None: ...
    def supply_page(self, page_index: int) -> bool: ...
    def supply_request(self, request: ClipPageRequest) -> bool: ...

class RealtimeEngine:
    def __init__(
        self,
        sample_rate: float = 48000.0,
        max_block_size: int = 128,
        *,
        command_capacity: int = 1024,
        telemetry_capacity: int = 1024,
    ) -> None: ...
    def close(self) -> None: ...
    def destroy(self) -> None: ...
    def delete(self) -> None: ...
    def __enter__(self) -> RealtimeEngine: ...
    def __exit__(self, *_exc: object) -> None: ...
    def prepare(
        self,
        sample_rate: float,
        max_block_size: int,
        command_capacity: int = 1024,
        telemetry_capacity: int = 1024,
    ) -> None: ...
    def play(self, render_frame: int = -1) -> None: ...
    def stop(self, render_frame: int = -1) -> None: ...
    def seek_sample(self, timeline_sample: int, render_frame: int = -1) -> None: ...
    def seek_ppq(self, ppq: float, render_frame: int = -1) -> None: ...
    def set_tempo(self, bpm: float) -> None: ...
    def set_time_signature(self, numerator: int, denominator: int) -> None: ...
    def sample_at_ppq(self, ppq: float) -> int: ...
    def set_loop(self, start_ppq: float, end_ppq: float, enabled: bool = True) -> None: ...
    def add_parameter(self, info: ParameterInfo) -> None: ...
    def parameter_count(self) -> int: ...
    def parameter_info_by_index(self, index: int) -> ParameterInfo: ...
    def parameter_info(self, id: int) -> ParameterInfo: ...
    def set_automation_lane(self, param_id: int, points: Sequence[AutomationPoint]) -> None: ...
    def automation_lane_count(self) -> int: ...
    def set_markers(self, markers: Sequence[EngineMarker]) -> None: ...
    def marker_count(self) -> int: ...
    def marker_by_index(self, index: int) -> EngineMarker: ...
    def marker(self, id: int) -> EngineMarker: ...
    def seek_marker(self, marker_id: int, render_frame: int = -1) -> None: ...
    def set_loop_from_markers(self, start_marker_id: int, end_marker_id: int) -> None: ...
    def set_metronome(self, config: EngineMetronomeConfig) -> None: ...
    def metronome(self) -> EngineMetronomeConfig: ...
    def count_in_end_sample(self, start_sample: int, bars: int) -> int: ...
    def set_clips(self, clips: Sequence[EngineClip]) -> None: ...
    def set_track_lanes(self, lanes: Sequence[int | Mapping[str, object]]) -> None: ...
    def set_track_buses(self, buses: Sequence[Mapping[str, object]]) -> None: ...
    def set_bus_strip_json(self, bus_id: int, scene_json: str) -> None: ...
    def set_track_strip_json(self, track_id: int, scene_json: str) -> None: ...
    def set_track_strip_eq_band(
        self, track_id: int, band_index: int, band: Mapping[str, object] | str
    ) -> None: ...
    def set_track_strip_eq_band_json(
        self, track_id: int, band_index: int, band_json: str
    ) -> None: ...
    def set_track_strip_insert_bypassed(
        self, track_id: int, insert_index: int, bypassed: bool, reset_on_bypass: bool = False
    ) -> None: ...
    def set_master_strip_json(self, scene_json: str) -> None: ...
    def set_master_strip_eq_band(
        self, band_index: int, band: Mapping[str, object] | str
    ) -> None: ...
    def set_master_strip_eq_band_json(self, band_index: int, band_json: str) -> None: ...
    def set_master_strip_insert_bypassed(
        self, insert_index: int, bypassed: bool, reset_on_bypass: bool = False
    ) -> None: ...
    def clip_count(self) -> int: ...
    def set_capture_buffer(self, num_channels: int, capacity_frames: int) -> None: ...
    def arm_capture(self, armed: bool = True) -> None: ...
    def set_capture_punch(
        self, start_sample: int, end_sample: int, enabled: bool = True
    ) -> None: ...
    def set_capture_source(self, source: str | int) -> None: ...
    def set_record_offset_samples(self, offset_samples: int) -> None: ...
    def set_input_monitor(self, enabled: bool, gain: float = 1.0) -> None: ...
    def reset_capture(self) -> None: ...
    def capture_status(self) -> EngineCaptureStatus: ...
    def captured_audio(self) -> list[list[float]]: ...
    def set_graph(self, spec: EngineGraphSpec) -> None: ...
    def graph_node_count(self) -> int: ...
    def graph_connection_count(self) -> int: ...
    def process(self, channels: Sequence[Sequence[float]]) -> list[list[float]]: ...
    def process_with_monitor(
        self, channels: Sequence[Sequence[float]]
    ) -> tuple[list[list[float]], list[list[float]]]: ...
    def render_offline(
        self, channels: Sequence[Sequence[float]], *, block_size: int = 128
    ) -> list[list[float]]: ...
    def bounce_offline(self, options: EngineBounceOptions) -> EngineBounceResult: ...
    def freeze_offline(self, options: EngineFreezeOptions) -> EngineFreezeResult: ...
    def drain_telemetry(self, max_records: int = 1024) -> list[EngineTelemetry]: ...
    def pop_clip_page_request(self) -> ClipPageRequest | None: ...
    def drain_meter_telemetry(self, max_records: int = 1024) -> list[MeterTelemetryRecord]: ...
    def set_parameter(self, param_id: int, value: float, render_frame: int = -1) -> None: ...
    def set_parameter_smoothed(
        self, param_id: int, value: float, render_frame: int = -1
    ) -> None: ...
    def set_solo_mute(
        self, lane_index: int, solo: bool, mute: bool, render_frame: int = -1
    ) -> None: ...
    def set_midi_clips(self, clips: Sequence[EngineMidiClipSchedule]) -> None: ...
    def push_midi_cc(
        self,
        destination_id: int,
        group: int,
        channel: int,
        controller: int,
        value: int,
        render_frame: int = -1,
    ) -> None: ...
    def push_midi_panic(self, render_frame: int = -1) -> None: ...
    def set_builtin_instrument(
        self, config: BuiltinSynthConfig | None = None, destination_id: int = 0
    ) -> None: ...
    def set_synth_instrument(
        self, patch: SynthPatch | str | None = None, destination_id: int = 0
    ) -> None: ...
    def load_soundfont(self, data: bytes | bytearray | memoryview) -> None: ...
    def set_sf2_instrument(
        self, config: Sf2InstrumentConfig | None = None, destination_id: int = 0
    ) -> None: ...
    def clear_midi_instrument(self, destination_id: int = 0) -> None: ...
    def midi_instrument_count(self) -> int: ...
    def bind_midi_cc(
        self,
        channel: int,
        controller: int,
        param_id: int,
        min_value: float = 0.0,
        max_value: float = 1.0,
    ) -> None: ...
    def clear_midi_cc_bindings(self) -> None: ...
    def midi_cc_binding_count(self) -> int: ...
    def clear_midi_fx(self, destination_id: int = 0) -> None: ...
    def set_midi_input_source(self, destination_id: int = 0) -> None: ...
    def clear_midi_input_source(self) -> None: ...
    def midi_input_pending_count(self) -> int: ...
    def push_midi_input_note_on(
        self,
        group: int,
        channel: int,
        note: int,
        velocity: int,
        port_time_samples: int = 0,
    ) -> None: ...
    def push_midi_input_note_off(
        self,
        group: int,
        channel: int,
        note: int,
        velocity: int = 0,
        port_time_samples: int = 0,
    ) -> None: ...
    def push_midi_input_cc(
        self,
        group: int,
        channel: int,
        controller: int,
        value: int,
        port_time_samples: int = 0,
    ) -> None: ...
    def push_midi_note_on(
        self,
        destination_id: int,
        group: int,
        channel: int,
        note: int,
        velocity: int,
        render_frame: int = -1,
    ) -> None: ...
    def push_midi_note_off(
        self,
        destination_id: int,
        group: int,
        channel: int,
        note: int,
        velocity: int = 0,
        render_frame: int = -1,
    ) -> None: ...
    def transport_state(self) -> TransportState: ...
