#include <array>
#include <cstring>
#include <memory>
#include <string>
#include <vector>

#if defined(SONARE_WITH_VOICE_CHANGER)
#include "editing/voice_changer/realtime_voice_changer.h"
#include "editing/voice_changer/voice_changer.h"
#endif
#include "core/audio.h"
#include "sonare_c.h"
#include "sonare_c_internal.h"

using namespace sonare;
using namespace sonare_c_detail;

namespace {

#if defined(SONARE_WITH_VOICE_CHANGER)
char* copy_c_string(const std::string& value) {
  char* out = new char[value.size() + 1];
  std::memcpy(out, value.c_str(), value.size() + 1);
  return out;
}
#endif

}  // namespace

#if defined(SONARE_WITH_VOICE_CHANGER)
struct SonareRealtimeVoiceChanger {
  editing::voice_changer::RealtimeVoiceChanger changer;
  int max_block_size = 0;
  int num_channels = 1;
  // Persistent scratch buffers for interleaved -> planar conversion so that
  // realtime callers don't trigger per-block heap allocations.
  std::vector<float> planar_scratch;        // num_channels * max_block_size
  std::vector<float*> planar_channel_ptrs;  // num_channels pointers into planar_scratch
};
#endif

SonareError sonare_voice_change(const float* samples, size_t length, int sample_rate,
                                float pitch_semitones, float formant_factor, float** out,
                                size_t* out_length) {
#if defined(SONARE_WITH_VOICE_CHANGER)
  if (!out || !out_length) return SONARE_ERROR_INVALID_PARAMETER;

  return run_offline(samples, length, sample_rate, [&](const Audio& audio) -> SonareError {
    editing::voice_changer::VoiceChangerConfig config;
    config.pitch_semitones = pitch_semitones;
    config.formant_factor = formant_factor;
    editing::voice_changer::VoiceChanger changer(config);
    Audio result = changer.process(audio);
    return copy_audio_result(result, out, out_length);
  });
#else
  SONARE_C_STUB_NOT_SUPPORTED(samples, length, sample_rate, pitch_semitones, formant_factor, out,
                              out_length);
#endif
}

#if defined(SONARE_WITH_VOICE_CHANGER)
namespace {

// Single source of truth for the POD ↔ C++ voice changer config bridge.
// X(cpp_path, pod_field) — cpp_path is a dotted C++ member path on the
// RealtimeVoiceChangerConfig struct; pod_field is the flat POD member on the
// SonareRealtimeVoiceChangerConfig struct. Both conversion directions are
// generated by re-expanding the same list, so asymmetric edits (e.g. only
// updating from_pod but forgetting to_pod) are no longer possible.
#define SONARE_VC_FIELDS(X)                               \
  X(input_gain_db, input_gain_db)                         \
  X(output_gain_db, output_gain_db)                       \
  X(wet_mix, wet_mix)                                     \
  X(retune.semitones, retune_semitones)                   \
  X(retune.mix, retune_mix)                               \
  X(retune.grain_size, retune_grain_size)                 \
  X(formant.factor, formant_factor)                       \
  X(formant.amount, formant_amount)                       \
  X(formant.body, formant_body)                           \
  X(formant.brightness, formant_brightness)               \
  X(formant.nasal, formant_nasal)                         \
  X(eq.highpass_hz, eq_highpass_hz)                       \
  X(eq.body_db, eq_body_db)                               \
  X(eq.presence_db, eq_presence_db)                       \
  X(eq.air_db, eq_air_db)                                 \
  X(gate.threshold_db, gate_threshold_db)                 \
  X(gate.attack_ms, gate_attack_ms)                       \
  X(gate.release_ms, gate_release_ms)                     \
  X(gate.range_db, gate_range_db)                         \
  X(compressor.threshold_db, compressor_threshold_db)     \
  X(compressor.ratio, compressor_ratio)                   \
  X(compressor.attack_ms, compressor_attack_ms)           \
  X(compressor.release_ms, compressor_release_ms)         \
  X(compressor.makeup_gain_db, compressor_makeup_gain_db) \
  X(deesser.frequency_hz, deesser_frequency_hz)           \
  X(deesser.threshold_db, deesser_threshold_db)           \
  X(deesser.ratio, deesser_ratio)                         \
  X(deesser.range_db, deesser_range_db)                   \
  X(reverb.mix, reverb_mix)                               \
  X(reverb.time_ms, reverb_time_ms)                       \
  X(reverb.damping, reverb_damping)                       \
  X(reverb.seed, reverb_seed)                             \
  X(limiter.ceiling_db, limiter_ceiling_db)               \
  X(limiter.release_ms, limiter_release_ms)               \
  X(limiter.isp_ceiling_dbtp, limiter_isp_ceiling_dbtp)

editing::voice_changer::RealtimeVoiceChangerConfig vc_config_from_pod(
    const SonareRealtimeVoiceChangerConfig& pod) {
  editing::voice_changer::RealtimeVoiceChangerConfig c;
#define X(cpp_path, pod_field) c.cpp_path = pod.pod_field;
  SONARE_VC_FIELDS(X)
#undef X
  // bool <-> int fields are handled explicitly (outside the float-oriented
  // X-macro) so the POD's non-zero==true convention is preserved.
  c.limiter.enable_isp_limiter = pod.limiter_enable_isp_limiter != 0;
  return c;
}

void vc_config_to_pod(const editing::voice_changer::RealtimeVoiceChangerConfig& c,
                      SonareRealtimeVoiceChangerConfig* pod) {
#define X(cpp_path, pod_field) pod->pod_field = c.cpp_path;
  SONARE_VC_FIELDS(X)
#undef X
  pod->limiter_enable_isp_limiter = c.limiter.enable_isp_limiter ? 1 : 0;
}

/// Single source of truth for the C ↔ C++ preset enum bridge. Adding a new
/// preset is a one-row table edit instead of two switch updates.
struct VcPresetMapping {
  SonareVoiceCharacterPreset c_enum;
  editing::voice_changer::VoiceCharacterPreset cpp_enum;
};

constexpr std::array<VcPresetMapping, 6> kVcPresetMapping = {{
    {SONARE_VC_PRESET_NEUTRAL_MONITOR,
     editing::voice_changer::VoiceCharacterPreset::NeutralMonitor},
    {SONARE_VC_PRESET_BRIGHT_IDOL, editing::voice_changer::VoiceCharacterPreset::BrightIdol},
    {SONARE_VC_PRESET_SOFT_WHISPER, editing::voice_changer::VoiceCharacterPreset::SoftWhisper},
    {SONARE_VC_PRESET_DEEP_NARRATOR, editing::voice_changer::VoiceCharacterPreset::DeepNarrator},
    {SONARE_VC_PRESET_ROBOT_MASCOT, editing::voice_changer::VoiceCharacterPreset::RobotMascot},
    {SONARE_VC_PRESET_DARK_VILLAIN, editing::voice_changer::VoiceCharacterPreset::DarkVillain},
}};

// The table must cover every value of the C++ enum or vc_preset_from_c silently
// falls back to NeutralMonitor for the new preset.
static_assert(
    kVcPresetMapping.size() ==
        static_cast<std::size_t>(editing::voice_changer::VoiceCharacterPreset::DarkVillain) + 1,
    "kVcPresetMapping is out of sync with VoiceCharacterPreset");

editing::voice_changer::VoiceCharacterPreset vc_preset_from_c(SonareVoiceCharacterPreset preset) {
  for (const auto& row : kVcPresetMapping) {
    if (row.c_enum == preset) return row.cpp_enum;
  }
  return editing::voice_changer::VoiceCharacterPreset::NeutralMonitor;
}

}  // namespace
#endif

SonareError sonare_realtime_voice_changer_preset_config(SonareVoiceCharacterPreset preset,
                                                        SonareRealtimeVoiceChangerConfig* out) {
#if defined(SONARE_WITH_VOICE_CHANGER)
  if (!out) return SONARE_ERROR_INVALID_PARAMETER;
  SONARE_C_TRY
  const auto config =
      editing::voice_changer::realtime_voice_changer_preset(vc_preset_from_c(preset));
  vc_config_to_pod(config, out);
  return SONARE_OK;
  SONARE_C_CATCH
#else
  SONARE_C_STUB_NOT_SUPPORTED(preset, out);
#endif
}

SonareError sonare_realtime_voice_changer_create(const SonareRealtimeVoiceChangerConfig* config,
                                                 int sample_rate, int max_block_size,
                                                 int num_channels,
                                                 SonareRealtimeVoiceChanger** out) {
#if defined(SONARE_WITH_VOICE_CHANGER)
  if (!out || sample_rate <= 0 || max_block_size <= 0 || num_channels < 1 || num_channels > 2) {
    return SONARE_ERROR_INVALID_PARAMETER;
  }
  *out = nullptr;
  SONARE_C_TRY
  editing::voice_changer::RealtimeVoiceChangerConfig cfg;
  if (config) {
    // Mirror the JSON entry path: reject NaN/Inf early (would propagate into
    // filter coefficients) rather than relying on normalize() alone. Range
    // sanitization still happens inside set_config().
    editing::voice_changer::RealtimeVoiceChangerConfig normalized;
    std::string error;
    if (!editing::voice_changer::validate_realtime_voice_changer_config(vc_config_from_pod(*config),
                                                                        &normalized, &error)) {
      return SONARE_ERROR_INVALID_PARAMETER;
    }
    cfg = normalized;
  } else {
    cfg = editing::voice_changer::realtime_voice_changer_preset(
        editing::voice_changer::VoiceCharacterPreset::NeutralMonitor);
  }
  auto handle = std::make_unique<SonareRealtimeVoiceChanger>();
  handle->changer.set_config(cfg);
  handle->changer.prepare(sample_rate, max_block_size, num_channels);
  handle->max_block_size = max_block_size;
  handle->num_channels = num_channels;
  const size_t scratch_floats =
      static_cast<size_t>(num_channels) * static_cast<size_t>(max_block_size);
  handle->planar_scratch.assign(scratch_floats, 0.0f);
  handle->planar_channel_ptrs.assign(static_cast<size_t>(num_channels), nullptr);
  for (int ch = 0; ch < num_channels; ++ch) {
    handle->planar_channel_ptrs[static_cast<size_t>(ch)] =
        handle->planar_scratch.data() +
        static_cast<size_t>(ch) * static_cast<size_t>(max_block_size);
  }
  *out = handle.release();
  return SONARE_OK;
  SONARE_C_CATCH
#else
  SONARE_C_STUB_NOT_SUPPORTED(config, sample_rate, max_block_size, num_channels, out);
#endif
}

SonareError sonare_realtime_voice_changer_set_config(
    SonareRealtimeVoiceChanger* handle, const SonareRealtimeVoiceChangerConfig* config) {
#if defined(SONARE_WITH_VOICE_CHANGER)
  if (!handle || !config) return SONARE_ERROR_INVALID_PARAMETER;
  SONARE_C_TRY
  editing::voice_changer::RealtimeVoiceChangerConfig normalized;
  std::string error;
  if (!editing::voice_changer::validate_realtime_voice_changer_config(vc_config_from_pod(*config),
                                                                      &normalized, &error)) {
    return SONARE_ERROR_INVALID_PARAMETER;
  }
  handle->changer.set_config(normalized);
  return SONARE_OK;
  SONARE_C_CATCH
#else
  SONARE_C_STUB_NOT_SUPPORTED(handle, config);
#endif
}

SonareError sonare_realtime_voice_changer_get_config(const SonareRealtimeVoiceChanger* handle,
                                                     SonareRealtimeVoiceChangerConfig* out) {
#if defined(SONARE_WITH_VOICE_CHANGER)
  if (!handle || !out) return SONARE_ERROR_INVALID_PARAMETER;
  SONARE_C_TRY
  vc_config_to_pod(handle->changer.config(), out);
  return SONARE_OK;
  SONARE_C_CATCH
#else
  SONARE_C_STUB_NOT_SUPPORTED(handle, out);
#endif
}

SonareError sonare_realtime_voice_changer_create_json(const char* preset_or_config_json,
                                                      int sample_rate, int max_block_size,
                                                      int num_channels,
                                                      SonareRealtimeVoiceChanger** out) {
#if defined(SONARE_WITH_VOICE_CHANGER)
  if (!out || sample_rate <= 0 || max_block_size <= 0 || num_channels < 1 || num_channels > 2) {
    return SONARE_ERROR_INVALID_PARAMETER;
  }
  *out = nullptr;
  SONARE_C_TRY
  const std::string config_text = preset_or_config_json && preset_or_config_json[0] != '\0'
                                      ? preset_or_config_json
                                      : "neutral-monitor";
  auto config = editing::voice_changer::realtime_voice_changer_config_from_json(config_text);
  auto handle = std::make_unique<SonareRealtimeVoiceChanger>();
  handle->changer.set_config(config);
  handle->changer.prepare(sample_rate, max_block_size, num_channels);
  handle->max_block_size = max_block_size;
  handle->num_channels = num_channels;
  // Pre-allocate planar scratch + channel-pointer table for interleaved
  // processing. Realtime-safe: never re-allocated after construction.
  const size_t scratch_floats =
      static_cast<size_t>(num_channels) * static_cast<size_t>(max_block_size);
  handle->planar_scratch.assign(scratch_floats, 0.0f);
  handle->planar_channel_ptrs.assign(static_cast<size_t>(num_channels), nullptr);
  for (int ch = 0; ch < num_channels; ++ch) {
    handle->planar_channel_ptrs[static_cast<size_t>(ch)] =
        handle->planar_scratch.data() +
        static_cast<size_t>(ch) * static_cast<size_t>(max_block_size);
  }
  *out = handle.release();
  return SONARE_OK;
  SONARE_C_CATCH
#else
  SONARE_C_STUB_NOT_SUPPORTED(preset_or_config_json, sample_rate, max_block_size, num_channels,
                              out);
#endif
}

void sonare_realtime_voice_changer_destroy(SonareRealtimeVoiceChanger* handle) {
#if defined(SONARE_WITH_VOICE_CHANGER)
  delete handle;
#else
  (void)handle;
#endif
}

SonareError sonare_realtime_voice_changer_reset(SonareRealtimeVoiceChanger* handle) {
#if defined(SONARE_WITH_VOICE_CHANGER)
  if (!handle) return SONARE_ERROR_INVALID_PARAMETER;
  SONARE_C_TRY
  handle->changer.reset();
  return SONARE_OK;
  SONARE_C_CATCH
#else
  SONARE_C_STUB_NOT_SUPPORTED(handle);
#endif
}

SonareError sonare_realtime_voice_changer_set_config_json(SonareRealtimeVoiceChanger* handle,
                                                          const char* preset_or_config_json) {
#if defined(SONARE_WITH_VOICE_CHANGER)
  if (!handle || !preset_or_config_json) return SONARE_ERROR_INVALID_PARAMETER;
  SONARE_C_TRY
  handle->changer.set_config(
      editing::voice_changer::realtime_voice_changer_config_from_json(preset_or_config_json));
  return SONARE_OK;
  SONARE_C_CATCH
#else
  SONARE_C_STUB_NOT_SUPPORTED(handle, preset_or_config_json);
#endif
}

SonareError sonare_realtime_voice_changer_process_mono(SonareRealtimeVoiceChanger* handle,
                                                       const float* input, float* output,
                                                       size_t num_samples) {
#if defined(SONARE_WITH_VOICE_CHANGER)
  if (!handle || (!input && num_samples > 0) || (!output && num_samples > 0)) {
    return SONARE_ERROR_INVALID_PARAMETER;
  }
  if (num_samples > static_cast<size_t>(handle->max_block_size)) {
    return SONARE_ERROR_INVALID_PARAMETER;
  }
  SONARE_C_TRY
  handle->changer.process_block(input, output, static_cast<int>(num_samples));
  return SONARE_OK;
  SONARE_C_CATCH
#else
  SONARE_C_STUB_NOT_SUPPORTED(handle, input, output, num_samples);
#endif
}

SonareError sonare_realtime_voice_changer_process_interleaved(SonareRealtimeVoiceChanger* handle,
                                                              const float* input, float* output,
                                                              size_t num_frames, int num_channels) {
#if defined(SONARE_WITH_VOICE_CHANGER)
  if (!handle || (!input && num_frames > 0) || (!output && num_frames > 0) || num_channels < 1 ||
      num_channels > handle->num_channels) {
    return SONARE_ERROR_INVALID_PARAMETER;
  }
  if (num_frames > static_cast<size_t>(handle->max_block_size)) {
    return SONARE_ERROR_INVALID_PARAMETER;
  }
  SONARE_C_TRY
  // RT-safe path: reuse the per-handle planar scratch (allocated in
  // create_json) and pointer table instead of allocating per call.
  const size_t stride = static_cast<size_t>(handle->max_block_size);
  for (int ch = 0; ch < num_channels; ++ch) {
    float* dst = handle->planar_scratch.data() + static_cast<size_t>(ch) * stride;
    for (size_t i = 0; i < num_frames; ++i) {
      dst[i] = input[i * static_cast<size_t>(num_channels) + static_cast<size_t>(ch)];
    }
  }
  handle->changer.process_block(handle->planar_channel_ptrs.data(), num_channels,
                                static_cast<int>(num_frames));
  for (int ch = 0; ch < num_channels; ++ch) {
    const float* src = handle->planar_scratch.data() + static_cast<size_t>(ch) * stride;
    for (size_t i = 0; i < num_frames; ++i) {
      output[i * static_cast<size_t>(num_channels) + static_cast<size_t>(ch)] = src[i];
    }
  }
  return SONARE_OK;
  SONARE_C_CATCH
#else
  SONARE_C_STUB_NOT_SUPPORTED(handle, input, output, num_frames, num_channels);
#endif
}

SonareError sonare_realtime_voice_changer_process_planar_stereo(SonareRealtimeVoiceChanger* handle,
                                                                float* left, float* right,
                                                                size_t num_frames) {
#if defined(SONARE_WITH_VOICE_CHANGER)
  if (!handle || (!left && num_frames > 0) || (!right && num_frames > 0)) {
    return SONARE_ERROR_INVALID_PARAMETER;
  }
  if (handle->num_channels < 2) {
    return SONARE_ERROR_INVALID_PARAMETER;
  }
  if (num_frames > static_cast<size_t>(handle->max_block_size)) {
    return SONARE_ERROR_INVALID_PARAMETER;
  }
  SONARE_C_TRY
  // Planar fast path: no interleave/deinterleave required, just point the
  // changer's process_block at the caller-owned buffers. Realtime-safe.
  float* channels[2] = {left, right};
  handle->changer.process_block(channels, 2, static_cast<int>(num_frames));
  return SONARE_OK;
  SONARE_C_CATCH
#else
  SONARE_C_STUB_NOT_SUPPORTED(handle, left, right, num_frames);
#endif
}

SonareError sonare_realtime_voice_changer_latency_samples(const SonareRealtimeVoiceChanger* handle,
                                                          int* out_latency_samples) {
#if defined(SONARE_WITH_VOICE_CHANGER)
  if (!handle || !out_latency_samples) return SONARE_ERROR_INVALID_PARAMETER;
  *out_latency_samples = handle->changer.latency_samples();
  return SONARE_OK;
#else
  SONARE_C_STUB_NOT_SUPPORTED(handle, out_latency_samples);
#endif
}

SonareError sonare_realtime_voice_changer_config_json(const SonareRealtimeVoiceChanger* handle,
                                                      char** out_json) {
#if defined(SONARE_WITH_VOICE_CHANGER)
  if (!handle || !out_json) return SONARE_ERROR_INVALID_PARAMETER;
  *out_json = nullptr;
  SONARE_C_TRY
  *out_json = copy_c_string(
      editing::voice_changer::realtime_voice_changer_config_to_json(handle->changer.config()));
  return SONARE_OK;
  SONARE_C_CATCH
#else
  SONARE_C_STUB_NOT_SUPPORTED(handle, out_json);
#endif
}

const char* sonare_realtime_voice_changer_preset_names(void) {
#if defined(SONARE_WITH_VOICE_CHANGER)
  // Backed by the canonical SONARE_REALTIME_VOICE_CHANGER_PRESET_IDS macro
  // so every binding shares a single source of truth.
  return SONARE_REALTIME_VOICE_CHANGER_PRESET_IDS;
#else
  return "";
#endif
}

#if defined(SONARE_WITH_VOICE_CHANGER)
// Keep the C++ ABI constant and the C macro in lock-step. The check lives here
// (the C ABI bridge layer) rather than inside editing/ to preserve the layer
// rule "editing/ must not depend on the public C API header sonare_c.h".
static_assert(editing::voice_changer::kVoiceChangerAbiVersion == SONARE_VOICE_CHANGER_ABI_VERSION,
              "C++ and C ABI version constants drifted");
#endif

uint32_t sonare_voice_changer_abi_version(void) {
#if defined(SONARE_WITH_VOICE_CHANGER)
  return editing::voice_changer::kVoiceChangerAbiVersion;
#else
  // Voice changer not compiled in: report 0 so bindings can detect the absence
  // (every shipped build with the feature is >= 1).
  return 0u;
#endif
}

const char* sonare_voice_character_preset_id(SonareVoiceCharacterPreset preset) {
#if defined(SONARE_WITH_VOICE_CHANGER)
  for (const auto& row : kVcPresetMapping) {
    if (row.c_enum == preset) {
      return editing::voice_changer::realtime_voice_changer_preset_id(row.cpp_enum);
    }
  }
  return nullptr;
#else
  (void)preset;
  return nullptr;
#endif
}

SonareError sonare_realtime_voice_changer_preset_json(const char* name, char** out_json) {
#if defined(SONARE_WITH_VOICE_CHANGER)
  if (!name || !out_json) return SONARE_ERROR_INVALID_PARAMETER;
  *out_json = nullptr;
  SONARE_C_TRY
  const auto preset = editing::voice_changer::realtime_voice_changer_preset_from_id(name);
  *out_json = copy_c_string(editing::voice_changer::realtime_voice_changer_preset_json(preset));
  return SONARE_OK;
  SONARE_C_CATCH
#else
  SONARE_C_STUB_NOT_SUPPORTED(name, out_json);
#endif
}

SonareError sonare_realtime_voice_changer_validate_preset_json(const char* json,
                                                               char** out_normalized_json,
                                                               char** out_error) {
#if defined(SONARE_WITH_VOICE_CHANGER)
  if (!json || !out_normalized_json || !out_error) return SONARE_ERROR_INVALID_PARAMETER;
  *out_normalized_json = nullptr;
  *out_error = nullptr;
  try {
    std::string normalized;
    std::string error;
    if (!editing::voice_changer::validate_realtime_voice_changer_preset_json(json, &normalized,
                                                                             &error)) {
      *out_error = copy_c_string(error.empty() ? "invalid preset JSON" : error);
      return SONARE_ERROR_INVALID_PARAMETER;
    }
    *out_normalized_json = copy_c_string(normalized);
    return SONARE_OK;
  } catch (const std::exception& ex) {
    *out_error = copy_c_string(ex.what());
    return SONARE_ERROR_INVALID_PARAMETER;
  }
#else
  SONARE_C_STUB_NOT_SUPPORTED(json, out_normalized_json, out_error);
#endif
}
