# Script mode (`cmake -P`): writes a header carrying the SHA-256 of the bank
# registry, so a library can say which registry state it was built against.
#
#   cmake [-DINPUT=<tools/bank-versions.json>] -DOUTPUT=<header> -P BankRegistryDigest.cmake
#
# Run at build time from an add_custom_command that depends on the registry, so
# a regenerated registry reaches the next build without a re-configure. With no
# INPUT the digest is null rather than a stale or invented value.

if(NOT DEFINED OUTPUT)
  message(FATAL_ERROR "BankRegistryDigest.cmake needs -DOUTPUT=<header>")
endif()

if(DEFINED INPUT AND EXISTS "${INPUT}")
  file(SHA256 "${INPUT}" _digest)
  set(_value "\"${_digest}\"")
else()
  set(_value "nullptr")
endif()

file(WRITE "${OUTPUT}" "// Generated by cmake/BankRegistryDigest.cmake from tools/bank-versions.json. Do not edit.
#pragma once

namespace sonare::midi::synth::generated {

inline constexpr const char* kBankRegistryDigest = ${_value};

}  // namespace sonare::midi::synth::generated
")
