# Script mode (`cmake -P`): writes a C++ source that embeds a binary file.
#
#   cmake -DINPUT=<file> -DOUTPUT=<file.cpp> -P EmbedBinary.cmake
#
# The generated unit defines `sonare::playback::kDefaultHrtf` and
# `sonare::playback::kDefaultHrtfSize`, declared in src/playback/default_hrtf.h.

if(NOT DEFINED INPUT OR NOT DEFINED OUTPUT)
  message(FATAL_ERROR "EmbedBinary.cmake needs -DINPUT=<file> and -DOUTPUT=<file.cpp>")
endif()

file(READ "${INPUT}" _hex HEX)
string(LENGTH "${_hex}" _hex_length)
math(EXPR _size "${_hex_length} / 2")
if(_size EQUAL 0)
  message(FATAL_ERROR "EmbedBinary.cmake: ${INPUT} is empty")
endif()

# Two hex digits per byte, sixteen bytes per line. CMake regexes have no {n}
# quantifier, so the line pattern is spelled out.
string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," _bytes "${_hex}")
string(REPEAT "0x[0-9a-f][0-9a-f]," 16 _line_pattern)
string(REGEX REPLACE "(${_line_pattern})" "\\1\n    " _bytes "${_bytes}")
get_filename_component(_input_name "${INPUT}" NAME)

set(_content "// Generated by cmake/EmbedBinary.cmake from ${_input_name}. Do not edit.
#include <cstddef>

#include \"playback/default_hrtf.h\"

namespace sonare::playback {

const unsigned char kDefaultHrtf[] = {
    ${_bytes}
};
const std::size_t kDefaultHrtfSize = ${_size};

}  // namespace sonare::playback
")

# Rewrite only on change so an unchanged input does not force a recompile.
if(EXISTS "${OUTPUT}")
  file(READ "${OUTPUT}" _existing)
  if(_existing STREQUAL _content)
    return()
  endif()
endif()
file(WRITE "${OUTPUT}" "${_content}")
